# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dotcms_rest_client import schemas  # noqa: F401


class RestCondition(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "conditionlet",
            "owningGroup",
            "operator",
        }
        
        class properties:
            owningGroup = schemas.StrSchema
            conditionlet = schemas.StrSchema
            operator = schemas.StrSchema
            
            
            class values(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def additional_properties() -> typing.Type['RestConditionValue']:
                        return RestConditionValue
                
                def __getitem__(self, name: typing.Union[str, ]) -> 'RestConditionValue':
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> 'RestConditionValue':
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: 'RestConditionValue',
                ) -> 'values':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            priority = schemas.Int32Schema
            __annotations__ = {
                "owningGroup": owningGroup,
                "conditionlet": conditionlet,
                "operator": operator,
                "values": values,
                "priority": priority,
            }
    
    conditionlet: MetaOapg.properties.conditionlet
    owningGroup: MetaOapg.properties.owningGroup
    operator: MetaOapg.properties.operator
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["owningGroup"]) -> MetaOapg.properties.owningGroup: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["conditionlet"]) -> MetaOapg.properties.conditionlet: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["operator"]) -> MetaOapg.properties.operator: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["values"]) -> MetaOapg.properties.values: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["priority"]) -> MetaOapg.properties.priority: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["owningGroup", "conditionlet", "operator", "values", "priority", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["owningGroup"]) -> MetaOapg.properties.owningGroup: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["conditionlet"]) -> MetaOapg.properties.conditionlet: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["operator"]) -> MetaOapg.properties.operator: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["values"]) -> typing.Union[MetaOapg.properties.values, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["priority"]) -> typing.Union[MetaOapg.properties.priority, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["owningGroup", "conditionlet", "operator", "values", "priority", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        conditionlet: typing.Union[MetaOapg.properties.conditionlet, str, ],
        owningGroup: typing.Union[MetaOapg.properties.owningGroup, str, ],
        operator: typing.Union[MetaOapg.properties.operator, str, ],
        values: typing.Union[MetaOapg.properties.values, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        priority: typing.Union[MetaOapg.properties.priority, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RestCondition':
        return super().__new__(
            cls,
            *_args,
            conditionlet=conditionlet,
            owningGroup=owningGroup,
            operator=operator,
            values=values,
            priority=priority,
            _configuration=_configuration,
            **kwargs,
        )

from dotcms_rest_client.model.rest_condition_value import RestConditionValue
