# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dotcms_rest_client import schemas  # noqa: F401


class UpdateTagForm(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "tagId",
            "siteId",
            "tagName",
        }
        
        class properties:
            siteId = schemas.StrSchema
            tagName = schemas.StrSchema
            tagId = schemas.StrSchema
            __annotations__ = {
                "siteId": siteId,
                "tagName": tagName,
                "tagId": tagId,
            }
    
    tagId: MetaOapg.properties.tagId
    siteId: MetaOapg.properties.siteId
    tagName: MetaOapg.properties.tagName
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["siteId"]) -> MetaOapg.properties.siteId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tagName"]) -> MetaOapg.properties.tagName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tagId"]) -> MetaOapg.properties.tagId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["siteId", "tagName", "tagId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["siteId"]) -> MetaOapg.properties.siteId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tagName"]) -> MetaOapg.properties.tagName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tagId"]) -> MetaOapg.properties.tagId: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["siteId", "tagName", "tagId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        tagId: typing.Union[MetaOapg.properties.tagId, str, ],
        siteId: typing.Union[MetaOapg.properties.siteId, str, ],
        tagName: typing.Union[MetaOapg.properties.tagName, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateTagForm':
        return super().__new__(
            cls,
            *_args,
            tagId=tagId,
            siteId=siteId,
            tagName=tagName,
            _configuration=_configuration,
            **kwargs,
        )
