import typing_extensions

from openapi_client.paths import PathValues
from openapi_client.apis.paths.v1_dotsaml_login_idp_config_id import V1DotsamlLoginIdpConfigId
from openapi_client.apis.paths.v1_dotsaml_logout_idp_config_id import V1DotsamlLogoutIdpConfigId
from openapi_client.apis.paths.v1_dotsaml_metadata_idp_config_id import V1DotsamlMetadataIdpConfigId
from openapi_client.apis.paths.v1_field_types import V1FieldTypes
from openapi_client.apis.paths.audit_publishing_get_bundle_id import AuditPublishingGetBundleId
from openapi_client.apis.paths.bundle_publisher_publish import BundlePublisherPublish
from openapi_client.apis.paths.bundle_all import BundleAll
from openapi_client.apis.paths.bundle_all_fail import BundleAllFail
from openapi_client.apis.paths.bundle_all_success import BundleAllSuccess
from openapi_client.apis.paths.bundle_ids import BundleIds
from openapi_client.apis.paths.bundle_olderthan_older_than import BundleOlderthanOlderThan
from openapi_client.apis.paths.bundle_deleteenvironmentpushhistory_params import BundleDeleteenvironmentpushhistoryParams
from openapi_client.apis.paths.bundle_deletepushhistory_params import BundleDeletepushhistoryParams
from openapi_client.apis.paths.bundle__download_bundle_id import BundleDownloadBundleId
from openapi_client.apis.paths.bundle_bundle_id_manifest import BundleBundleIdManifest
from openapi_client.apis.paths.bundle__generate import BundleGenerate
from openapi_client.apis.paths.bundle_bundle_id_assets import BundleBundleIdAssets
from openapi_client.apis.paths.bundle_getunsendbundles_params import BundleGetunsendbundlesParams
from openapi_client.apis.paths.bundle_updatebundle_params import BundleUpdatebundleParams
from openapi_client.apis.paths.bundle import Bundle
from openapi_client.apis.paths.bundle_sync import BundleSync
from openapi_client.apis.paths.config_delete_endpoint import ConfigDeleteEndpoint
from openapi_client.apis.paths.config_delete_environment import ConfigDeleteEnvironment
from openapi_client.apis.paths.config_regenerate_key import ConfigRegenerateKey
from openapi_client.apis.paths.config_save_company_auth_type_info import ConfigSaveCompanyAuthTypeInfo
from openapi_client.apis.paths.config_save_company_basic_info import ConfigSaveCompanyBasicInfo
from openapi_client.apis.paths.config_save_company_locale_info import ConfigSaveCompanyLocaleInfo
from openapi_client.apis.paths.config_save_company_logo import ConfigSaveCompanyLogo
from openapi_client.apis.paths.cluster_get_es_config_properties_params import ClusterGetESConfigPropertiesParams
from openapi_client.apis.paths.cluster_license_repo_status import ClusterLicenseRepoStatus
from openapi_client.apis.paths.cluster_get_nodes_status_params import ClusterGetNodesStatusParams
from openapi_client.apis.paths.cluster_remove_params import ClusterRemoveParams
from openapi_client.apis.paths.cluster_test import ClusterTest
from openapi_client.apis.paths.content_can_lock_params import ContentCanLockParams
from openapi_client.apis.paths.content_params import ContentParams
from openapi_client.apis.paths.content_indexcount_query import ContentIndexcountQuery
from openapi_client.apis.paths.content_indexsearch_query_sortby_sortby_limit_limit_offset_offset import ContentIndexsearchQuerySortbySortbyLimitLimitOffsetOffset
from openapi_client.apis.paths.content_lock_params import ContentLockParams
from openapi_client.apis.paths.content__search import ContentSearch
from openapi_client.apis.paths.content_unlock_params import ContentUnlockParams
from openapi_client.apis.paths.environment_loadenvironments_params import EnvironmentLoadenvironmentsParams
from openapi_client.apis.paths.integrity_checkintegrity_params import IntegrityCheckintegrityParams
from openapi_client.apis.paths.integrity_check_integrity_process_status_params import IntegrityCheckIntegrityProcessStatusParams
from openapi_client.apis.paths.integrity_discardconflicts_params import IntegrityDiscardconflictsParams
from openapi_client.apis.paths.integrity_fixconflicts_params import IntegrityFixconflictsParams
from openapi_client.apis.paths.integrity__fixconflictsfromremote import IntegrityFixconflictsfromremote
from openapi_client.apis.paths.integrity__generateintegritydata import IntegrityGenerateintegritydata
from openapi_client.apis.paths.integrity_request_id_integrity_data import IntegrityRequestIdIntegrityData
from openapi_client.apis.paths.integrity_get_integrity_result_params import IntegrityGetIntegrityResultParams
from openapi_client.apis.paths.portlet_layout_params import PortletLayoutParams
from openapi_client.apis.paths.portlet_params import PortletParams
from openapi_client.apis.paths.license_apply_license import LicenseApplyLicense
from openapi_client.apis.paths.license_delete_params import LicenseDeleteParams
from openapi_client.apis.paths.license_free_params import LicenseFreeParams
from openapi_client.apis.paths.license_all_params import LicenseAllParams
from openapi_client.apis.paths.license_pick_params import LicensePickParams
from openapi_client.apis.paths.license_upload_params import LicenseUploadParams
from openapi_client.apis.paths.license_request_code_params import LicenseRequestCodeParams
from openapi_client.apis.paths.license_reset_license_params import LicenseResetLicenseParams
from openapi_client.apis.paths.osgi_get_installed_bundles_params import OsgiGetInstalledBundlesParams
from openapi_client.apis.paths.osgi__process_exports_bundle import OsgiProcessExportsBundle
from openapi_client.apis.paths.osgi import Osgi
from openapi_client.apis.paths.v1_publishqueue import V1Publishqueue
from openapi_client.apis.paths.restexample_layout_params import RestexampleLayoutParams
from openapi_client.apis.paths.restexample_test_params import RestexampleTestParams
from openapi_client.apis.paths.role_loadbyid_params import RoleLoadbyidParams
from openapi_client.apis.paths.role_loadbyname_params import RoleLoadbynameParams
from openapi_client.apis.paths.role_loadchildren_params import RoleLoadchildrenParams
from openapi_client.apis.paths.rulesengine_layout_params import RulesengineLayoutParams
from openapi_client.apis.paths.structure_path import StructurePath
from openapi_client.apis.paths.v1_tags import V1Tags
from openapi_client.apis.paths.v1_tags_tag_id import V1TagsTagId
from openapi_client.apis.paths.v1_tags_inode_inode import V1TagsInodeInode
from openapi_client.apis.paths.v1_tags_name_or_id import V1TagsNameOrId
from openapi_client.apis.paths.v1_tags_user_user_id import V1TagsUserUserId
from openapi_client.apis.paths.v1_tags_import import V1TagsImport
from openapi_client.apis.paths.v1_tags_tag_name_or_id_inode_inode import V1TagsTagNameOrIdInodeInode
from openapi_client.apis.paths.test_resource_test_get_params import TestResourceTestGetParams
from openapi_client.apis.paths.test_resource_test_post import TestResourceTestPost
from openapi_client.apis.paths.user_getloggedinuser_params import UserGetloggedinuserParams
from openapi_client.apis.paths.util_encode_query_param_value_params import UtilEncodeQueryParamValueParams
from openapi_client.apis.paths.widget_params import WidgetParams
from openapi_client.apis.paths.v1_apps import V1Apps
from openapi_client.apis.paths.v1_apps_key_site_id import V1AppsKeySiteId
from openapi_client.apis.paths.v1_apps_key import V1AppsKey
from openapi_client.apis.paths.v1_apps_export import V1AppsExport
from openapi_client.apis.paths.v1_apps_import import V1AppsImport
from openapi_client.apis.paths.v1_apitoken_token_id import V1ApitokenTokenId
from openapi_client.apis.paths.v1_apitoken_user_id_tokens import V1ApitokenUserIdTokens
from openapi_client.apis.paths.v1_apitoken_token_id_jwt import V1ApitokenTokenIdJwt
from openapi_client.apis.paths.v1_apitoken_remote import V1ApitokenRemote
from openapi_client.apis.paths.v1_apitoken import V1Apitoken
from openapi_client.apis.paths.v1_apitoken_token_id_revoke import V1ApitokenTokenIdRevoke
from openapi_client.apis.paths.v1_apitoken_users_userid_revoke import V1ApitokenUsersUseridRevoke
from openapi_client.apis.paths.v1_apitoken_users_revoke import V1ApitokenUsersRevoke
from openapi_client.apis.paths.v1_authentication import V1Authentication
from openapi_client.apis.paths.v1_authentication_log_in_user import V1AuthenticationLogInUser
from openapi_client.apis.paths.v1_authentication_api_token import V1AuthenticationApiToken
from openapi_client.apis.paths.v1_forgotpassword import V1Forgotpassword
from openapi_client.apis.paths.v1_loginform import V1Loginform
from openapi_client.apis.paths.v1_logout import V1Logout
from openapi_client.apis.paths.v1_change_password import V1ChangePassword
from openapi_client.apis.paths.v1_browser import V1Browser
from openapi_client.apis.paths.v1_browser_selectedfolder import V1BrowserSelectedfolder
from openapi_client.apis.paths.v1_browsertree_sitename_sitename_uri import V1BrowsertreeSitenameSitenameUri
from openapi_client.apis.paths.v1_browsertree_sitename_sitename_uri_uri import V1BrowsertreeSitenameSitenameUriUri
from openapi_client.apis.paths.v1_categories import V1Categories
from openapi_client.apis.paths.v1_categories__export import V1CategoriesExport
from openapi_client.apis.paths.v1_categories_id_or_key import V1CategoriesIdOrKey
from openapi_client.apis.paths.v1_categories_children import V1CategoriesChildren
from openapi_client.apis.paths.v1_categories__import import V1CategoriesImport
from openapi_client.apis.paths.v1_categories__sort import V1CategoriesSort
from openapi_client.apis.paths.v1_containers__archive import V1ContainersArchive
from openapi_client.apis.paths.v1_containers__bulkarchive import V1ContainersBulkarchive
from openapi_client.apis.paths.v1_containers__bulkdelete import V1ContainersBulkdelete
from openapi_client.apis.paths.v1_containers__bulkpublish import V1ContainersBulkpublish
from openapi_client.apis.paths.v1_containers__bulkunarchive import V1ContainersBulkunarchive
from openapi_client.apis.paths.v1_containers__bulkunpublish import V1ContainersBulkunpublish
from openapi_client.apis.paths.v1_containers_container_id_content_contentlet_id import V1ContainersContainerIdContentContentletId
from openapi_client.apis.paths.v1_containers_content_contentlet_id import V1ContainersContentContentletId
from openapi_client.apis.paths.v1_containers_container_id_form_form_id import V1ContainersContainerIdFormFormId
from openapi_client.apis.paths.v1_containers_form_form_id import V1ContainersFormFormId
from openapi_client.apis.paths.v1_containers_id__copy import V1ContainersIdCopy
from openapi_client.apis.paths.v1_containers import V1Containers
from openapi_client.apis.paths.v1_containers_live import V1ContainersLive
from openapi_client.apis.paths.v1_containers_working import V1ContainersWorking
from openapi_client.apis.paths.v1_containers__publish import V1ContainersPublish
from openapi_client.apis.paths.v1_containers_delete_container_id_content_contentlet_id_uid_uid import V1ContainersDeleteContainerIdContentContentletIdUidUid
from openapi_client.apis.paths.v1_containers__unarchive import V1ContainersUnarchive
from openapi_client.apis.paths.v1_containers__unpublish import V1ContainersUnpublish
from openapi_client.apis.paths.v1_contentrelationships_params import V1ContentrelationshipsParams
from openapi_client.apis.paths.v1_content__canlock_inode_or_identifier import V1ContentCanlockInodeOrIdentifier
from openapi_client.apis.paths.v1_content_inode_or_identifier import V1ContentInodeOrIdentifier
from openapi_client.apis.paths.v1_content_related import V1ContentRelated
from openapi_client.apis.paths.v1_content_versions_inode import V1ContentVersionsInode
from openapi_client.apis.paths.v1_content_versions import V1ContentVersions
from openapi_client.apis.paths.v1_content_resourcelinks_field_field import V1ContentResourcelinksFieldField
from openapi_client.apis.paths.v1_content_resourcelinks import V1ContentResourcelinks
from openapi_client.apis.paths.v1_contenttype_base_variable_name__copy import V1ContenttypeBaseVariableNameCopy
from openapi_client.apis.paths.v1_contenttype import V1Contenttype
from openapi_client.apis.paths.v1_contenttype_id_id_or_var import V1ContenttypeIdIdOrVar
from openapi_client.apis.paths.v1_contenttype__filter import V1ContenttypeFilter
from openapi_client.apis.paths.v1_contenttype_basetypes import V1ContenttypeBasetypes
from openapi_client.apis.paths.v1_contenttype_type_id_fields import V1ContenttypeTypeIdFields
from openapi_client.apis.paths.v1_contenttype_type_id_fields_id_field_id import V1ContenttypeTypeIdFieldsIdFieldId
from openapi_client.apis.paths.v1_contenttype_type_id_fields_var_field_var import V1ContenttypeTypeIdFieldsVarFieldVar
from openapi_client.apis.paths.v1_contenttype_type_id_fields_id_field_id_variables import V1ContenttypeTypeIdFieldsIdFieldIdVariables
from openapi_client.apis.paths.v1_contenttype_type_id_fields_var_field_var_variables import V1ContenttypeTypeIdFieldsVarFieldVarVariables
from openapi_client.apis.paths.v1_contenttype_type_id_fields_id_field_id_variables_id_field_var_id import V1ContenttypeTypeIdFieldsIdFieldIdVariablesIdFieldVarId
from openapi_client.apis.paths.v1_contenttype_type_id_fields_var_field_var_variables_id_field_var_id import V1ContenttypeTypeIdFieldsVarFieldVarVariablesIdFieldVarId
from openapi_client.apis.paths.ws_v1_system_events import WsV1SystemEvents
from openapi_client.apis.paths.ws_v1_system_syncevents import WsV1SystemSyncevents
from openapi_client.apis.paths.v1_experiments_experiment_id_variants import V1ExperimentsExperimentIdVariants
from openapi_client.apis.paths.v1_experiments_experiment_id__archive import V1ExperimentsExperimentIdArchive
from openapi_client.apis.paths.v1_experiments import V1Experiments
from openapi_client.apis.paths.v1_experiments_experiment_id import V1ExperimentsExperimentId
from openapi_client.apis.paths.v1_experiments_experiment_id_goals_primary import V1ExperimentsExperimentIdGoalsPrimary
from openapi_client.apis.paths.v1_experiments_experiment_id_targeting_conditions_id import V1ExperimentsExperimentIdTargetingConditionsId
from openapi_client.apis.paths.v1_experiments_experiment_id_variants_name import V1ExperimentsExperimentIdVariantsName
from openapi_client.apis.paths.v1_experiments_experiment_id__end import V1ExperimentsExperimentIdEnd
from openapi_client.apis.paths.v1_experiments_id import V1ExperimentsId
from openapi_client.apis.paths.v1_experiments_is_user_included import V1ExperimentsIsUserIncluded
from openapi_client.apis.paths.v1_experiments_experiment_id__start import V1ExperimentsExperimentIdStart
from openapi_client.apis.paths.v1_content_fileassets_inode_resourcelink import V1ContentFileassetsInodeResourcelink
from openapi_client.apis.paths.v1_folder_createfolders_site_name import V1FolderCreatefoldersSiteName
from openapi_client.apis.paths.v1_folder_site_name import V1FolderSiteName
from openapi_client.apis.paths.v1_folder_folder_id import V1FolderFolderId
from openapi_client.apis.paths.v1_folder_by_path import V1FolderByPath
from openapi_client.apis.paths.v1_folder_site_id_site_id_path_path import V1FolderSiteIdSiteIdPathPath
from openapi_client.apis.paths.v1_folder_sitename_site_name_uri_uri import V1FolderSitenameSiteNameUriUri
from openapi_client.apis.paths.v1_folder_id_file_browser_selected import V1FolderIdFileBrowserSelected
from openapi_client.apis.paths.v1_form_id_or_var_success_callback import V1FormIdOrVarSuccessCallback
from openapi_client.apis.paths.v1_esindex_activate_params import V1EsindexActivateParams
from openapi_client.apis.paths.v1_esindex_clear_params import V1EsindexClearParams
from openapi_client.apis.paths.v1_esindex_close_params import V1EsindexCloseParams
from openapi_client.apis.paths.v1_esindex_create_params import V1EsindexCreateParams
from openapi_client.apis.paths.v1_esindex_deactivate_params import V1EsindexDeactivateParams
from openapi_client.apis.paths.v1_esindex_failed import V1EsindexFailed
from openapi_client.apis.paths.v1_esindex_index_name import V1EsindexIndexName
from openapi_client.apis.paths.v1_esindex_cache import V1EsindexCache
from openapi_client.apis.paths.v1_esindex_active_params import V1EsindexActiveParams
from openapi_client.apis.paths.v1_esindex_cluster import V1EsindexCluster
from openapi_client.apis.paths.v1_esindex import V1Esindex
from openapi_client.apis.paths.v1_esindex_reindex import V1EsindexReindex
from openapi_client.apis.paths.v1_esindex_indexlist_params import V1EsindexIndexlistParams
from openapi_client.apis.paths.v1_esindex_open_params import V1EsindexOpenParams
from openapi_client.apis.paths.v1_esindex_optimize import V1EsindexOptimize
from openapi_client.apis.paths.v1_languages_i18n import V1LanguagesI18n
from openapi_client.apis.paths.v1_languages import V1Languages
from openapi_client.apis.paths.v1_jvm import V1Jvm
from openapi_client.apis.paths.v1_maintenance__download_assets import V1MaintenanceDownloadAssets
from openapi_client.apis.paths.v1_maintenance__download_db import V1MaintenanceDownloadDb
from openapi_client.apis.paths.v1_maintenance__download_log_file_name import V1MaintenanceDownloadLogFileName
from openapi_client.apis.paths.v1_maintenance__download_starter import V1MaintenanceDownloadStarter
from openapi_client.apis.paths.v1_maintenance__download_starter_with_assets import V1MaintenanceDownloadStarterWithAssets
from openapi_client.apis.paths.v1_maintenance__pg_dump_available import V1MaintenancePgDumpAvailable
from openapi_client.apis.paths.v1_maintenance__shutdown import V1MaintenanceShutdown
from openapi_client.apis.paths.v1_menu import V1Menu
from openapi_client.apis.paths.v1_notification_delete import V1NotificationDelete
from openapi_client.apis.paths.v1_notification_id_id import V1NotificationIdId
from openapi_client.apis.paths.v1_notification_get_new_notifications_count import V1NotificationGetNewNotificationsCount
from openapi_client.apis.paths.v1_notification_get_notifications_params import V1NotificationGetNotificationsParams
from openapi_client.apis.paths.v1_notification_mark_as_read import V1NotificationMarkAsRead
from openapi_client.apis.paths.v1_nav_uri import V1NavUri
from openapi_client.apis.paths.v1_page_page_id_content import V1PagePageIdContent
from openapi_client.apis.paths.v1_page_copy_content import V1PageCopyContent
from openapi_client.apis.paths.v1_page_page_id__deepcopy import V1PagePageIdDeepcopy
from openapi_client.apis.paths.v1_page_page_id_content_tree import V1PagePageIdContentTree
from openapi_client.apis.paths.v1_page_page_id_render_versions import V1PagePageIdRenderVersions
from openapi_client.apis.paths.v1_page_page_id_personas import V1PagePageIdPersonas
from openapi_client.apis.paths.v1_page_json_uri import V1PageJsonUri
from openapi_client.apis.paths.v1_page_render_uri import V1PageRenderUri
from openapi_client.apis.paths.v1_page_render_html_uri import V1PageRenderHTMLUri
from openapi_client.apis.paths.v1_page_layout import V1PageLayout
from openapi_client.apis.paths.v1_page_page_id_layout import V1PagePageIdLayout
from openapi_client.apis.paths.v1_page_search import V1PageSearch
from openapi_client.apis.paths.v1_personalization_pagepersonas import V1PersonalizationPagepersonas
from openapi_client.apis.paths.v1_personalization_pagepersonas_page_page_id_personalization_personalization import V1PersonalizationPagepersonasPagePageIdPersonalizationPersonalization
from openapi_client.apis.paths.v1_personas import V1Personas
from openapi_client.apis.paths.v1_personas_id import V1PersonasId
from openapi_client.apis.paths.v1_portlet_custom_portlet_id__addtolayout_layout_id import V1PortletCustomPortletIdAddtolayoutLayoutId
from openapi_client.apis.paths.v1_portlet_custom import V1PortletCustom
from openapi_client.apis.paths.v1_portlet_custom_portlet_id import V1PortletCustomPortletId
from openapi_client.apis.paths.v1_portlet_portlet_id_portlet_id import V1PortletPortletIdPortletId
from openapi_client.apis.paths.v1_portlet_portlet_id_portlet_id_role_id_role_id import V1PortletPortletIdPortletIdRoleIdRoleId
from openapi_client.apis.paths.v1_portlet_portlet_id__doesuserhaveaccess import V1PortletPortletIdDoesuserhaveaccess
from openapi_client.apis.paths.v1_portlet_portlet_id import V1PortletPortletId
from openapi_client.apis.paths.v1_portlet__actionurl_content_type_variable import V1PortletActionurlContentTypeVariable
from openapi_client.apis.paths.v1_toolgroups_layout_id__addtouser import V1ToolgroupsLayoutIdAddtouser
from openapi_client.apis.paths.v1_toolgroups_layout_id__removefromuser import V1ToolgroupsLayoutIdRemovefromuser
from openapi_client.apis.paths.v1_toolgroups_layout_id__user_has_layout import V1ToolgroupsLayoutIdUserHasLayout
from openapi_client.apis.paths.v1_pushpublish_filters_filter_key import V1PushpublishFiltersFilterKey
from openapi_client.apis.paths.v1_pushpublish_filters import V1PushpublishFilters
from openapi_client.apis.paths.v1_relationships_cardinalities import V1RelationshipsCardinalities
from openapi_client.apis.paths.v1_relationships import V1Relationships
from openapi_client.apis.paths.v1_site_site_id__archive import V1SiteSiteIdArchive
from openapi_client.apis.paths.v1_site__copy import V1SiteCopy
from openapi_client.apis.paths.v1_site import V1Site
from openapi_client.apis.paths.v1_site_current_site import V1SiteCurrentSite
from openapi_client.apis.paths.v1_site_default_site import V1SiteDefaultSite
from openapi_client.apis.paths.v1_site_site_id import V1SiteSiteId
from openapi_client.apis.paths.v1_site_thumbnails import V1SiteThumbnails
from openapi_client.apis.paths.v1_site__byname import V1SiteByname
from openapi_client.apis.paths.v1_site_site_id_setup_progress import V1SiteSiteIdSetupProgress
from openapi_client.apis.paths.v1_site_variable_site_id import V1SiteVariableSiteId
from openapi_client.apis.paths.v1_site_site_id__makedefault import V1SiteSiteIdMakedefault
from openapi_client.apis.paths.v1_site_site_id__publish import V1SiteSiteIdPublish
from openapi_client.apis.paths.v1_site_variable import V1SiteVariable
from openapi_client.apis.paths.v1_site_switch import V1SiteSwitch
from openapi_client.apis.paths.v1_site_switch_id import V1SiteSwitchId
from openapi_client.apis.paths.v1_site_site_id__unarchive import V1SiteSiteIdUnarchive
from openapi_client.apis.paths.v1_site_site_id__unpublish import V1SiteSiteIdUnpublish
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_rules import V1SitesSiteIdRuleengineRules
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_rules_rule_id import V1SitesSiteIdRuleengineRulesRuleId
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_actions import V1SitesSiteIdRuleengineActions
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_actions_action_id import V1SitesSiteIdRuleengineActionsActionId
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_rules_rule_id_condition_groups import V1SitesSiteIdRuleengineRulesRuleIdConditionGroups
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_rules_rule_id_condition_groups_condition_group_id import V1SitesSiteIdRuleengineRulesRuleIdConditionGroupsConditionGroupId
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_rules_rule_id_condition_groups_group_id import V1SitesSiteIdRuleengineRulesRuleIdConditionGroupsGroupId
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_conditions import V1SitesSiteIdRuleengineConditions
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_conditions_condition_id import V1SitesSiteIdRuleengineConditionsConditionId
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_conditions_condition_id_condition_values import V1SitesSiteIdRuleengineConditionsConditionIdConditionValues
from openapi_client.apis.paths.v1_sites_site_id_ruleengine_conditions_condition_id_condition_values_value_id import V1SitesSiteIdRuleengineConditionsConditionIdConditionValuesValueId
from openapi_client.apis.paths.v1_appconfiguration import V1Appconfiguration
from openapi_client.apis.paths.v1_configuration_config import V1ConfigurationConfig
from openapi_client.apis.paths.v1_configuration import V1Configuration
from openapi_client.apis.paths.v1_configuration__validate_company_email import V1ConfigurationValidateCompanyEmail
from openapi_client.apis.paths.v1_upgradetask import V1Upgradetask
from openapi_client.apis.paths.v1_caches_provider_provider_flush import V1CachesProviderProviderFlush
from openapi_client.apis.paths.v1_caches_provider_provider_flush_group import V1CachesProviderProviderFlushGroup
from openapi_client.apis.paths.v1_caches_provider_provider_flush_group_id import V1CachesProviderProviderFlushGroupId
from openapi_client.apis.paths.v1_caches_provider_provider_keys_group import V1CachesProviderProviderKeysGroup
from openapi_client.apis.paths.v1_caches_provider_provider_object_group_id import V1CachesProviderProviderObjectGroupId
from openapi_client.apis.paths.v1_caches_provider_provider_objects_group import V1CachesProviderProviderObjectsGroup
from openapi_client.apis.paths.v1_caches_providers_group import V1CachesProvidersGroup
from openapi_client.apis.paths.v1_caches_provider_provider_group import V1CachesProviderProviderGroup
from openapi_client.apis.paths.v1_system_i18n_lang_rsrc import V1SystemI18nLangRsrc
from openapi_client.apis.paths.v1_logger import V1Logger
from openapi_client.apis.paths.v1_logger_logger_name import V1LoggerLoggerName
from openapi_client.apis.paths.v1_system_status_alive import V1SystemStatusAlive
from openapi_client.apis.paths.v1_system_status import V1SystemStatus
from openapi_client.apis.paths.v1_permissions__bycontent import V1PermissionsBycontent
from openapi_client.apis.paths.v1_permissions__bypermissiontype import V1PermissionsBypermissiontype
from openapi_client.apis.paths.v1_redis_key import V1RedisKey
from openapi_client.apis.paths.v1_redis_hash_key import V1RedisHashKey
from openapi_client.apis.paths.v1_redis_echo_message import V1RedisEchoMessage
from openapi_client.apis.paths.v1_redis_incr_key import V1RedisIncrKey
from openapi_client.apis.paths.v1_redis_ping import V1RedisPing
from openapi_client.apis.paths.v1_redis import V1Redis
from openapi_client.apis.paths.v1_redis_hash import V1RedisHash
from openapi_client.apis.paths.v1_roles_checkuserroles_userid_user_id_roleids_role_ids import V1RolesCheckuserrolesUseridUserIdRoleidsRoleIds
from openapi_client.apis.paths.v1_roles_layouts import V1RolesLayouts
from openapi_client.apis.paths.v1_roles_role_id_layouts import V1RolesRoleIdLayouts
from openapi_client.apis.paths.v1_roles_roleid import V1RolesRoleid
from openapi_client.apis.paths.v1_roles import V1Roles
from openapi_client.apis.paths.v1_roles_roleid_rolehierarchyanduserroles import V1RolesRoleidRolehierarchyanduserroles
from openapi_client.apis.paths.v1_roles__search import V1RolesSearch
from openapi_client.apis.paths.v1_system_ruleengine_actionlets import V1SystemRuleengineActionlets
from openapi_client.apis.paths.v1_system_ruleengine_conditionlets import V1SystemRuleengineConditionlets
from openapi_client.apis.paths.v1_logs_file_name__tail import V1LogsFileNameTail
from openapi_client.apis.paths.v1_temp_by_url import V1TempByUrl
from openapi_client.apis.paths.v1_temp import V1Temp
from openapi_client.apis.paths.v1_templates__archive import V1TemplatesArchive
from openapi_client.apis.paths.v1_templates_template_id__copy import V1TemplatesTemplateIdCopy
from openapi_client.apis.paths.v1_templates import V1Templates
from openapi_client.apis.paths.v1_templates_template_id_live import V1TemplatesTemplateIdLive
from openapi_client.apis.paths.v1_templates_template_id_working import V1TemplatesTemplateIdWorking
from openapi_client.apis.paths.v1_templates__publish import V1TemplatesPublish
from openapi_client.apis.paths.v1_templates__savepublish import V1TemplatesSavepublish
from openapi_client.apis.paths.v1_templates_draft import V1TemplatesDraft
from openapi_client.apis.paths.v1_templates__unarchive import V1TemplatesUnarchive
from openapi_client.apis.paths.v1_templates__unpublish import V1TemplatesUnpublish
from openapi_client.apis.paths.v1_themes_id_id import V1ThemesIdId
from openapi_client.apis.paths.v1_themes import V1Themes
from openapi_client.apis.paths.v1_users_filter_params import V1UsersFilterParams
from openapi_client.apis.paths.v1_users_loginas import V1UsersLoginas
from openapi_client.apis.paths.v1_users_login_as_data import V1UsersLoginAsData
from openapi_client.apis.paths.v1_users_logoutas import V1UsersLogoutas
from openapi_client.apis.paths.v1_users_current import V1UsersCurrent
from openapi_client.apis.paths.v1_versionables_versionable_inode__bringback import V1VersionablesVersionableInodeBringback
from openapi_client.apis.paths.v1_versionables_versionable_inode import V1VersionablesVersionableInode
from openapi_client.apis.paths.v1_versionables_versionable_inode_or_identifier import V1VersionablesVersionableInodeOrIdentifier
from openapi_client.apis.paths.vtl_folder import VtlFolder
from openapi_client.apis.paths.vtl_folder_path_param import VtlFolderPathParam
from openapi_client.apis.paths.vtl_dynamic_path_param import VtlDynamicPathParam
from openapi_client.apis.paths.vtl_dynamic import VtlDynamic
from openapi_client.apis.paths.v1_workflow_steps import V1WorkflowSteps
from openapi_client.apis.paths.v1_workflow_schemes_scheme_id_copy import V1WorkflowSchemesSchemeIdCopy
from openapi_client.apis.paths.v1_workflow_actions_action_id import V1WorkflowActionsActionId
from openapi_client.apis.paths.v1_workflow_steps_step_id_actions_action_id import V1WorkflowStepsStepIdActionsActionId
from openapi_client.apis.paths.v1_workflow_actionlets_actionlet_id import V1WorkflowActionletsActionletId
from openapi_client.apis.paths.v1_workflow_schemes_scheme_id import V1WorkflowSchemesSchemeId
from openapi_client.apis.paths.v1_workflow_steps_step_id import V1WorkflowStepsStepId
from openapi_client.apis.paths.v1_workflow_system_actions_identifier import V1WorkflowSystemActionsIdentifier
from openapi_client.apis.paths.v1_workflow_actions_action_id_condition import V1WorkflowActionsActionIdCondition
from openapi_client.apis.paths.v1_workflow_schemes_scheme_id_export import V1WorkflowSchemesSchemeIdExport
from openapi_client.apis.paths.v1_workflow_actionlets import V1WorkflowActionlets
from openapi_client.apis.paths.v1_workflow_actions_action_id_actionlets import V1WorkflowActionsActionIdActionlets
from openapi_client.apis.paths.v1_workflow_schemes_scheme_id_actions import V1WorkflowSchemesSchemeIdActions
from openapi_client.apis.paths.v1_workflow_schemes_actions_system_action import V1WorkflowSchemesActionsSystemAction
from openapi_client.apis.paths.v1_workflow_steps_step_id_actions import V1WorkflowStepsStepIdActions
from openapi_client.apis.paths.v1_workflow_schemes_schemescontenttypes_content_type_id import V1WorkflowSchemesSchemescontenttypesContentTypeId
from openapi_client.apis.paths.v1_workflow_contentlet_inode_actions import V1WorkflowContentletInodeActions
from openapi_client.apis.paths.v1_workflow_defaultactions_contenttype_content_type_id import V1WorkflowDefaultactionsContenttypeContentTypeId
from openapi_client.apis.paths.v1_workflow_defaultactions_schemes import V1WorkflowDefaultactionsSchemes
from openapi_client.apis.paths.v1_workflow_initialactions_contenttype_content_type_id import V1WorkflowInitialactionsContenttypeContentTypeId
from openapi_client.apis.paths.v1_workflow_schemes import V1WorkflowSchemes
from openapi_client.apis.paths.v1_workflow_schemes_scheme_id_steps import V1WorkflowSchemesSchemeIdSteps
from openapi_client.apis.paths.v1_workflow_contenttypes_content_type_var_or_id_system_actions import V1WorkflowContenttypesContentTypeVarOrIdSystemActions
from openapi_client.apis.paths.v1_workflow_schemes_scheme_id_system_actions import V1WorkflowSchemesSchemeIdSystemActions
from openapi_client.apis.paths.v1_workflow_actions_fire import V1WorkflowActionsFire
from openapi_client.apis.paths.v1_workflow_actions_default_fire_system_action import V1WorkflowActionsDefaultFireSystemAction
from openapi_client.apis.paths.v1_workflow_actions_default_firemultipart_system_action import V1WorkflowActionsDefaultFiremultipartSystemAction
from openapi_client.apis.paths.v1_workflow_actions_action_id_fire import V1WorkflowActionsActionIdFire
from openapi_client.apis.paths.v1_workflow_actions_action_id_firemultipart import V1WorkflowActionsActionIdFiremultipart
from openapi_client.apis.paths.v1_workflow_contentlet_actions__bulkfire import V1WorkflowContentletActionsBulkfire
from openapi_client.apis.paths.v1_workflow_contentlet_actions_bulk_fire import V1WorkflowContentletActionsBulkFire
from openapi_client.apis.paths.v1_workflow_contentlet_actions_bulk import V1WorkflowContentletActionsBulk
from openapi_client.apis.paths.v1_workflow_system_actions_workflow_action_id import V1WorkflowSystemActionsWorkflowActionId
from openapi_client.apis.paths.v1_workflow_schemes_import import V1WorkflowSchemesImport
from openapi_client.apis.paths.v1_workflow_reorder_steps_step_id_actions_action_id import V1WorkflowReorderStepsStepIdActionsActionId
from openapi_client.apis.paths.v1_workflow_reorder_step_step_id_order_order import V1WorkflowReorderStepStepIdOrderOrder
from openapi_client.apis.paths.v1_workflow_actions import V1WorkflowActions
from openapi_client.apis.paths.v1_workflow_system_actions import V1WorkflowSystemActions
from openapi_client.apis.paths.v2_contenttype_type_id_or_var_name_fields import V2ContenttypeTypeIdOrVarNameFields
from openapi_client.apis.paths.v2_contenttype_type_id_or_var_name_fields_id_field_id import V2ContenttypeTypeIdOrVarNameFieldsIdFieldId
from openapi_client.apis.paths.v2_contenttype_type_id_or_var_name_fields_var_field_var import V2ContenttypeTypeIdOrVarNameFieldsVarFieldVar
from openapi_client.apis.paths.v2_languages_language_id import V2LanguagesLanguageId
from openapi_client.apis.paths.v2_languages_id_languageid import V2LanguagesIdLanguageid
from openapi_client.apis.paths.v2_languages_language_keys import V2LanguagesLanguageKeys
from openapi_client.apis.paths.v2_languages_language_tag import V2LanguagesLanguageTag
from openapi_client.apis.paths.v2_languages_i18n import V2LanguagesI18n
from openapi_client.apis.paths.v2_languages import V2Languages
from openapi_client.apis.paths.v2_languages_language__makedefault import V2LanguagesLanguageMakedefault
from openapi_client.apis.paths.v3_contenttype_type_id_or_var_name_fields import V3ContenttypeTypeIdOrVarNameFields
from openapi_client.apis.paths.v3_contenttype_type_id_or_var_name_fields_move import V3ContenttypeTypeIdOrVarNameFieldsMove
from openapi_client.apis.paths.v3_contenttype_type_id_or_var_name_fields_id import V3ContenttypeTypeIdOrVarNameFieldsId
from openapi_client.apis.paths.es_layout_params import EsLayoutParams
from openapi_client.apis.paths.es_search import EsSearch
from openapi_client.apis.paths.es_raw import EsRaw
from openapi_client.apis.paths.personas_layout_params import PersonasLayoutParams
from openapi_client.apis.paths.personas_sites_id import PersonasSitesId
from openapi_client.apis.paths.application_wadl_path import ApplicationWadlPath
from openapi_client.apis.paths.application_wadl import ApplicationWadl

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.V1_DOTSAML_LOGIN_IDP_CONFIG_ID: V1DotsamlLoginIdpConfigId,
        PathValues.V1_DOTSAML_LOGOUT_IDP_CONFIG_ID: V1DotsamlLogoutIdpConfigId,
        PathValues.V1_DOTSAML_METADATA_IDP_CONFIG_ID: V1DotsamlMetadataIdpConfigId,
        PathValues.V1_FIELD_TYPES: V1FieldTypes,
        PathValues.AUDIT_PUBLISHING_GET_BUNDLE_ID: AuditPublishingGetBundleId,
        PathValues.BUNDLE_PUBLISHER_PUBLISH: BundlePublisherPublish,
        PathValues.BUNDLE_ALL: BundleAll,
        PathValues.BUNDLE_ALL_FAIL: BundleAllFail,
        PathValues.BUNDLE_ALL_SUCCESS: BundleAllSuccess,
        PathValues.BUNDLE_IDS: BundleIds,
        PathValues.BUNDLE_OLDERTHAN_OLDER_THAN: BundleOlderthanOlderThan,
        PathValues.BUNDLE_DELETEENVIRONMENTPUSHHISTORY_PARAMS: BundleDeleteenvironmentpushhistoryParams,
        PathValues.BUNDLE_DELETEPUSHHISTORY_PARAMS: BundleDeletepushhistoryParams,
        PathValues.BUNDLE__DOWNLOAD_BUNDLE_ID: BundleDownloadBundleId,
        PathValues.BUNDLE_BUNDLE_ID_MANIFEST: BundleBundleIdManifest,
        PathValues.BUNDLE__GENERATE: BundleGenerate,
        PathValues.BUNDLE_BUNDLE_ID_ASSETS: BundleBundleIdAssets,
        PathValues.BUNDLE_GETUNSENDBUNDLES_PARAMS: BundleGetunsendbundlesParams,
        PathValues.BUNDLE_UPDATEBUNDLE_PARAMS: BundleUpdatebundleParams,
        PathValues.BUNDLE: Bundle,
        PathValues.BUNDLE_SYNC: BundleSync,
        PathValues.CONFIG_DELETE_ENDPOINT: ConfigDeleteEndpoint,
        PathValues.CONFIG_DELETE_ENVIRONMENT: ConfigDeleteEnvironment,
        PathValues.CONFIG_REGENERATE_KEY: ConfigRegenerateKey,
        PathValues.CONFIG_SAVE_COMPANY_AUTH_TYPE_INFO: ConfigSaveCompanyAuthTypeInfo,
        PathValues.CONFIG_SAVE_COMPANY_BASIC_INFO: ConfigSaveCompanyBasicInfo,
        PathValues.CONFIG_SAVE_COMPANY_LOCALE_INFO: ConfigSaveCompanyLocaleInfo,
        PathValues.CONFIG_SAVE_COMPANY_LOGO: ConfigSaveCompanyLogo,
        PathValues.CLUSTER_GET_ESCONFIG_PROPERTIES_PARAMS: ClusterGetESConfigPropertiesParams,
        PathValues.CLUSTER_LICENSE_REPO_STATUS: ClusterLicenseRepoStatus,
        PathValues.CLUSTER_GET_NODES_STATUS_PARAMS: ClusterGetNodesStatusParams,
        PathValues.CLUSTER_REMOVE_PARAMS: ClusterRemoveParams,
        PathValues.CLUSTER_TEST: ClusterTest,
        PathValues.CONTENT_CAN_LOCK_PARAMS: ContentCanLockParams,
        PathValues.CONTENT_PARAMS: ContentParams,
        PathValues.CONTENT_INDEXCOUNT_QUERY: ContentIndexcountQuery,
        PathValues.CONTENT_INDEXSEARCH_QUERY_SORTBY_SORTBY_LIMIT_LIMIT_OFFSET_OFFSET: ContentIndexsearchQuerySortbySortbyLimitLimitOffsetOffset,
        PathValues.CONTENT_LOCK_PARAMS: ContentLockParams,
        PathValues.CONTENT__SEARCH: ContentSearch,
        PathValues.CONTENT_UNLOCK_PARAMS: ContentUnlockParams,
        PathValues.ENVIRONMENT_LOADENVIRONMENTS_PARAMS: EnvironmentLoadenvironmentsParams,
        PathValues.INTEGRITY_CHECKINTEGRITY_PARAMS: IntegrityCheckintegrityParams,
        PathValues.INTEGRITY_CHECK_INTEGRITY_PROCESS_STATUS_PARAMS: IntegrityCheckIntegrityProcessStatusParams,
        PathValues.INTEGRITY_DISCARDCONFLICTS_PARAMS: IntegrityDiscardconflictsParams,
        PathValues.INTEGRITY_FIXCONFLICTS_PARAMS: IntegrityFixconflictsParams,
        PathValues.INTEGRITY__FIXCONFLICTSFROMREMOTE: IntegrityFixconflictsfromremote,
        PathValues.INTEGRITY__GENERATEINTEGRITYDATA: IntegrityGenerateintegritydata,
        PathValues.INTEGRITY_REQUEST_ID_INTEGRITY_DATA: IntegrityRequestIdIntegrityData,
        PathValues.INTEGRITY_GET_INTEGRITY_RESULT_PARAMS: IntegrityGetIntegrityResultParams,
        PathValues.PORTLET_LAYOUT_PARAMS: PortletLayoutParams,
        PathValues.PORTLET_PARAMS: PortletParams,
        PathValues.LICENSE_APPLY_LICENSE: LicenseApplyLicense,
        PathValues.LICENSE_DELETE_PARAMS: LicenseDeleteParams,
        PathValues.LICENSE_FREE_PARAMS: LicenseFreeParams,
        PathValues.LICENSE_ALL_PARAMS: LicenseAllParams,
        PathValues.LICENSE_PICK_PARAMS: LicensePickParams,
        PathValues.LICENSE_UPLOAD_PARAMS: LicenseUploadParams,
        PathValues.LICENSE_REQUEST_CODE_PARAMS: LicenseRequestCodeParams,
        PathValues.LICENSE_RESET_LICENSE_PARAMS: LicenseResetLicenseParams,
        PathValues.OSGI_GET_INSTALLED_BUNDLES_PARAMS: OsgiGetInstalledBundlesParams,
        PathValues.OSGI__PROCESS_EXPORTS_BUNDLE: OsgiProcessExportsBundle,
        PathValues.OSGI: Osgi,
        PathValues.V1_PUBLISHQUEUE: V1Publishqueue,
        PathValues.RESTEXAMPLE_LAYOUT_PARAMS: RestexampleLayoutParams,
        PathValues.RESTEXAMPLE_TEST_PARAMS: RestexampleTestParams,
        PathValues.ROLE_LOADBYID_PARAMS: RoleLoadbyidParams,
        PathValues.ROLE_LOADBYNAME_PARAMS: RoleLoadbynameParams,
        PathValues.ROLE_LOADCHILDREN_PARAMS: RoleLoadchildrenParams,
        PathValues.RULESENGINE_LAYOUT_PARAMS: RulesengineLayoutParams,
        PathValues.STRUCTURE_PATH: StructurePath,
        PathValues.V1_TAGS: V1Tags,
        PathValues.V1_TAGS_TAG_ID: V1TagsTagId,
        PathValues.V1_TAGS_INODE_INODE: V1TagsInodeInode,
        PathValues.V1_TAGS_NAME_OR_ID: V1TagsNameOrId,
        PathValues.V1_TAGS_USER_USER_ID: V1TagsUserUserId,
        PathValues.V1_TAGS_IMPORT: V1TagsImport,
        PathValues.V1_TAGS_TAG_NAME_OR_ID_INODE_INODE: V1TagsTagNameOrIdInodeInode,
        PathValues.TEST_RESOURCE_TEST_GET_PARAMS: TestResourceTestGetParams,
        PathValues.TEST_RESOURCE_TEST_POST: TestResourceTestPost,
        PathValues.USER_GETLOGGEDINUSER_PARAMS: UserGetloggedinuserParams,
        PathValues.UTIL_ENCODE_QUERY_PARAM_VALUE_PARAMS: UtilEncodeQueryParamValueParams,
        PathValues.WIDGET_PARAMS: WidgetParams,
        PathValues.V1_APPS: V1Apps,
        PathValues.V1_APPS_KEY_SITE_ID: V1AppsKeySiteId,
        PathValues.V1_APPS_KEY: V1AppsKey,
        PathValues.V1_APPS_EXPORT: V1AppsExport,
        PathValues.V1_APPS_IMPORT: V1AppsImport,
        PathValues.V1_APITOKEN_TOKEN_ID: V1ApitokenTokenId,
        PathValues.V1_APITOKEN_USER_ID_TOKENS: V1ApitokenUserIdTokens,
        PathValues.V1_APITOKEN_TOKEN_ID_JWT: V1ApitokenTokenIdJwt,
        PathValues.V1_APITOKEN_REMOTE: V1ApitokenRemote,
        PathValues.V1_APITOKEN: V1Apitoken,
        PathValues.V1_APITOKEN_TOKEN_ID_REVOKE: V1ApitokenTokenIdRevoke,
        PathValues.V1_APITOKEN_USERS_USERID_REVOKE: V1ApitokenUsersUseridRevoke,
        PathValues.V1_APITOKEN_USERS_REVOKE: V1ApitokenUsersRevoke,
        PathValues.V1_AUTHENTICATION: V1Authentication,
        PathValues.V1_AUTHENTICATION_LOG_IN_USER: V1AuthenticationLogInUser,
        PathValues.V1_AUTHENTICATION_APITOKEN: V1AuthenticationApiToken,
        PathValues.V1_FORGOTPASSWORD: V1Forgotpassword,
        PathValues.V1_LOGINFORM: V1Loginform,
        PathValues.V1_LOGOUT: V1Logout,
        PathValues.V1_CHANGE_PASSWORD: V1ChangePassword,
        PathValues.V1_BROWSER: V1Browser,
        PathValues.V1_BROWSER_SELECTEDFOLDER: V1BrowserSelectedfolder,
        PathValues.V1_BROWSERTREE_SITENAME_SITENAME_URI: V1BrowsertreeSitenameSitenameUri,
        PathValues.V1_BROWSERTREE_SITENAME_SITENAME_URI_URI: V1BrowsertreeSitenameSitenameUriUri,
        PathValues.V1_CATEGORIES: V1Categories,
        PathValues.V1_CATEGORIES__EXPORT: V1CategoriesExport,
        PathValues.V1_CATEGORIES_ID_OR_KEY: V1CategoriesIdOrKey,
        PathValues.V1_CATEGORIES_CHILDREN: V1CategoriesChildren,
        PathValues.V1_CATEGORIES__IMPORT: V1CategoriesImport,
        PathValues.V1_CATEGORIES__SORT: V1CategoriesSort,
        PathValues.V1_CONTAINERS__ARCHIVE: V1ContainersArchive,
        PathValues.V1_CONTAINERS__BULKARCHIVE: V1ContainersBulkarchive,
        PathValues.V1_CONTAINERS__BULKDELETE: V1ContainersBulkdelete,
        PathValues.V1_CONTAINERS__BULKPUBLISH: V1ContainersBulkpublish,
        PathValues.V1_CONTAINERS__BULKUNARCHIVE: V1ContainersBulkunarchive,
        PathValues.V1_CONTAINERS__BULKUNPUBLISH: V1ContainersBulkunpublish,
        PathValues.V1_CONTAINERS_CONTAINER_ID_CONTENT_CONTENTLET_ID: V1ContainersContainerIdContentContentletId,
        PathValues.V1_CONTAINERS_CONTENT_CONTENTLET_ID: V1ContainersContentContentletId,
        PathValues.V1_CONTAINERS_CONTAINER_ID_FORM_FORM_ID: V1ContainersContainerIdFormFormId,
        PathValues.V1_CONTAINERS_FORM_FORM_ID: V1ContainersFormFormId,
        PathValues.V1_CONTAINERS_ID__COPY: V1ContainersIdCopy,
        PathValues.V1_CONTAINERS: V1Containers,
        PathValues.V1_CONTAINERS_LIVE: V1ContainersLive,
        PathValues.V1_CONTAINERS_WORKING: V1ContainersWorking,
        PathValues.V1_CONTAINERS__PUBLISH: V1ContainersPublish,
        PathValues.V1_CONTAINERS_DELETE_CONTAINER_ID_CONTENT_CONTENTLET_ID_UID_UID: V1ContainersDeleteContainerIdContentContentletIdUidUid,
        PathValues.V1_CONTAINERS__UNARCHIVE: V1ContainersUnarchive,
        PathValues.V1_CONTAINERS__UNPUBLISH: V1ContainersUnpublish,
        PathValues.V1_CONTENTRELATIONSHIPS_PARAMS: V1ContentrelationshipsParams,
        PathValues.V1_CONTENT__CANLOCK_INODE_OR_IDENTIFIER: V1ContentCanlockInodeOrIdentifier,
        PathValues.V1_CONTENT_INODE_OR_IDENTIFIER: V1ContentInodeOrIdentifier,
        PathValues.V1_CONTENT_RELATED: V1ContentRelated,
        PathValues.V1_CONTENT_VERSIONS_INODE: V1ContentVersionsInode,
        PathValues.V1_CONTENT_VERSIONS: V1ContentVersions,
        PathValues.V1_CONTENT_RESOURCELINKS_FIELD_FIELD: V1ContentResourcelinksFieldField,
        PathValues.V1_CONTENT_RESOURCELINKS: V1ContentResourcelinks,
        PathValues.V1_CONTENTTYPE_BASE_VARIABLE_NAME__COPY: V1ContenttypeBaseVariableNameCopy,
        PathValues.V1_CONTENTTYPE: V1Contenttype,
        PathValues.V1_CONTENTTYPE_ID_ID_OR_VAR: V1ContenttypeIdIdOrVar,
        PathValues.V1_CONTENTTYPE__FILTER: V1ContenttypeFilter,
        PathValues.V1_CONTENTTYPE_BASETYPES: V1ContenttypeBasetypes,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS: V1ContenttypeTypeIdFields,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_ID_FIELD_ID: V1ContenttypeTypeIdFieldsIdFieldId,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_VAR_FIELD_VAR: V1ContenttypeTypeIdFieldsVarFieldVar,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_ID_FIELD_ID_VARIABLES: V1ContenttypeTypeIdFieldsIdFieldIdVariables,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_VAR_FIELD_VAR_VARIABLES: V1ContenttypeTypeIdFieldsVarFieldVarVariables,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_ID_FIELD_ID_VARIABLES_ID_FIELD_VAR_ID: V1ContenttypeTypeIdFieldsIdFieldIdVariablesIdFieldVarId,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_VAR_FIELD_VAR_VARIABLES_ID_FIELD_VAR_ID: V1ContenttypeTypeIdFieldsVarFieldVarVariablesIdFieldVarId,
        PathValues.WS_V1_SYSTEM_EVENTS: WsV1SystemEvents,
        PathValues.WS_V1_SYSTEM_SYNCEVENTS: WsV1SystemSyncevents,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_VARIANTS: V1ExperimentsExperimentIdVariants,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID__ARCHIVE: V1ExperimentsExperimentIdArchive,
        PathValues.V1_EXPERIMENTS: V1Experiments,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID: V1ExperimentsExperimentId,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_GOALS_PRIMARY: V1ExperimentsExperimentIdGoalsPrimary,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_TARGETING_CONDITIONS_ID: V1ExperimentsExperimentIdTargetingConditionsId,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_VARIANTS_NAME: V1ExperimentsExperimentIdVariantsName,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID__END: V1ExperimentsExperimentIdEnd,
        PathValues.V1_EXPERIMENTS_ID: V1ExperimentsId,
        PathValues.V1_EXPERIMENTS_IS_USER_INCLUDED: V1ExperimentsIsUserIncluded,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID__START: V1ExperimentsExperimentIdStart,
        PathValues.V1_CONTENT_FILEASSETS_INODE_RESOURCELINK: V1ContentFileassetsInodeResourcelink,
        PathValues.V1_FOLDER_CREATEFOLDERS_SITE_NAME: V1FolderCreatefoldersSiteName,
        PathValues.V1_FOLDER_SITE_NAME: V1FolderSiteName,
        PathValues.V1_FOLDER_FOLDER_ID: V1FolderFolderId,
        PathValues.V1_FOLDER_BY_PATH: V1FolderByPath,
        PathValues.V1_FOLDER_SITE_ID_SITE_ID_PATH_PATH: V1FolderSiteIdSiteIdPathPath,
        PathValues.V1_FOLDER_SITENAME_SITE_NAME_URI_URI: V1FolderSitenameSiteNameUriUri,
        PathValues.V1_FOLDER_ID_FILEBROWSERSELECTED: V1FolderIdFileBrowserSelected,
        PathValues.V1_FORM_ID_OR_VAR_SUCCESS_CALLBACK: V1FormIdOrVarSuccessCallback,
        PathValues.V1_ESINDEX_ACTIVATE_PARAMS: V1EsindexActivateParams,
        PathValues.V1_ESINDEX_CLEAR_PARAMS: V1EsindexClearParams,
        PathValues.V1_ESINDEX_CLOSE_PARAMS: V1EsindexCloseParams,
        PathValues.V1_ESINDEX_CREATE_PARAMS: V1EsindexCreateParams,
        PathValues.V1_ESINDEX_DEACTIVATE_PARAMS: V1EsindexDeactivateParams,
        PathValues.V1_ESINDEX_FAILED: V1EsindexFailed,
        PathValues.V1_ESINDEX_INDEX_NAME: V1EsindexIndexName,
        PathValues.V1_ESINDEX_CACHE: V1EsindexCache,
        PathValues.V1_ESINDEX_ACTIVE_PARAMS: V1EsindexActiveParams,
        PathValues.V1_ESINDEX_CLUSTER: V1EsindexCluster,
        PathValues.V1_ESINDEX: V1Esindex,
        PathValues.V1_ESINDEX_REINDEX: V1EsindexReindex,
        PathValues.V1_ESINDEX_INDEXLIST_PARAMS: V1EsindexIndexlistParams,
        PathValues.V1_ESINDEX_OPEN_PARAMS: V1EsindexOpenParams,
        PathValues.V1_ESINDEX_OPTIMIZE: V1EsindexOptimize,
        PathValues.V1_LANGUAGES_I18N: V1LanguagesI18n,
        PathValues.V1_LANGUAGES: V1Languages,
        PathValues.V1_JVM: V1Jvm,
        PathValues.V1_MAINTENANCE__DOWNLOAD_ASSETS: V1MaintenanceDownloadAssets,
        PathValues.V1_MAINTENANCE__DOWNLOAD_DB: V1MaintenanceDownloadDb,
        PathValues.V1_MAINTENANCE__DOWNLOAD_LOG_FILE_NAME: V1MaintenanceDownloadLogFileName,
        PathValues.V1_MAINTENANCE__DOWNLOAD_STARTER: V1MaintenanceDownloadStarter,
        PathValues.V1_MAINTENANCE__DOWNLOAD_STARTER_WITH_ASSETS: V1MaintenanceDownloadStarterWithAssets,
        PathValues.V1_MAINTENANCE__PG_DUMP_AVAILABLE: V1MaintenancePgDumpAvailable,
        PathValues.V1_MAINTENANCE__SHUTDOWN: V1MaintenanceShutdown,
        PathValues.V1_MENU: V1Menu,
        PathValues.V1_NOTIFICATION_DELETE: V1NotificationDelete,
        PathValues.V1_NOTIFICATION_ID_ID: V1NotificationIdId,
        PathValues.V1_NOTIFICATION_GET_NEW_NOTIFICATIONS_COUNT: V1NotificationGetNewNotificationsCount,
        PathValues.V1_NOTIFICATION_GET_NOTIFICATIONS_PARAMS: V1NotificationGetNotificationsParams,
        PathValues.V1_NOTIFICATION_MARK_AS_READ: V1NotificationMarkAsRead,
        PathValues.V1_NAV_URI: V1NavUri,
        PathValues.V1_PAGE_PAGE_ID_CONTENT: V1PagePageIdContent,
        PathValues.V1_PAGE_COPY_CONTENT: V1PageCopyContent,
        PathValues.V1_PAGE_PAGE_ID__DEEPCOPY: V1PagePageIdDeepcopy,
        PathValues.V1_PAGE_PAGE_ID_CONTENT_TREE: V1PagePageIdContentTree,
        PathValues.V1_PAGE_PAGE_ID_RENDER_VERSIONS: V1PagePageIdRenderVersions,
        PathValues.V1_PAGE_PAGE_ID_PERSONAS: V1PagePageIdPersonas,
        PathValues.V1_PAGE_JSON_URI: V1PageJsonUri,
        PathValues.V1_PAGE_RENDER_URI: V1PageRenderUri,
        PathValues.V1_PAGE_RENDER_HTML_URI: V1PageRenderHTMLUri,
        PathValues.V1_PAGE_LAYOUT: V1PageLayout,
        PathValues.V1_PAGE_PAGE_ID_LAYOUT: V1PagePageIdLayout,
        PathValues.V1_PAGE_SEARCH: V1PageSearch,
        PathValues.V1_PERSONALIZATION_PAGEPERSONAS: V1PersonalizationPagepersonas,
        PathValues.V1_PERSONALIZATION_PAGEPERSONAS_PAGE_PAGE_ID_PERSONALIZATION_PERSONALIZATION: V1PersonalizationPagepersonasPagePageIdPersonalizationPersonalization,
        PathValues.V1_PERSONAS: V1Personas,
        PathValues.V1_PERSONAS_ID: V1PersonasId,
        PathValues.V1_PORTLET_CUSTOM_PORTLET_ID__ADDTOLAYOUT_LAYOUT_ID: V1PortletCustomPortletIdAddtolayoutLayoutId,
        PathValues.V1_PORTLET_CUSTOM: V1PortletCustom,
        PathValues.V1_PORTLET_CUSTOM_PORTLET_ID: V1PortletCustomPortletId,
        PathValues.V1_PORTLET_PORTLET_ID_PORTLET_ID: V1PortletPortletIdPortletId,
        PathValues.V1_PORTLET_PORTLET_ID_PORTLET_ID_ROLE_ID_ROLE_ID: V1PortletPortletIdPortletIdRoleIdRoleId,
        PathValues.V1_PORTLET_PORTLET_ID__DOESUSERHAVEACCESS: V1PortletPortletIdDoesuserhaveaccess,
        PathValues.V1_PORTLET_PORTLET_ID: V1PortletPortletId,
        PathValues.V1_PORTLET__ACTIONURL_CONTENT_TYPE_VARIABLE: V1PortletActionurlContentTypeVariable,
        PathValues.V1_TOOLGROUPS_LAYOUT_ID__ADDTOUSER: V1ToolgroupsLayoutIdAddtouser,
        PathValues.V1_TOOLGROUPS_LAYOUT_ID__REMOVEFROMUSER: V1ToolgroupsLayoutIdRemovefromuser,
        PathValues.V1_TOOLGROUPS_LAYOUT_ID__USER_HAS_LAYOUT: V1ToolgroupsLayoutIdUserHasLayout,
        PathValues.V1_PUSHPUBLISH_FILTERS_FILTER_KEY: V1PushpublishFiltersFilterKey,
        PathValues.V1_PUSHPUBLISH_FILTERS: V1PushpublishFilters,
        PathValues.V1_RELATIONSHIPS_CARDINALITIES: V1RelationshipsCardinalities,
        PathValues.V1_RELATIONSHIPS: V1Relationships,
        PathValues.V1_SITE_SITE_ID__ARCHIVE: V1SiteSiteIdArchive,
        PathValues.V1_SITE__COPY: V1SiteCopy,
        PathValues.V1_SITE: V1Site,
        PathValues.V1_SITE_CURRENT_SITE: V1SiteCurrentSite,
        PathValues.V1_SITE_DEFAULT_SITE: V1SiteDefaultSite,
        PathValues.V1_SITE_SITE_ID: V1SiteSiteId,
        PathValues.V1_SITE_THUMBNAILS: V1SiteThumbnails,
        PathValues.V1_SITE__BYNAME: V1SiteByname,
        PathValues.V1_SITE_SITE_ID_SETUP_PROGRESS: V1SiteSiteIdSetupProgress,
        PathValues.V1_SITE_VARIABLE_SITE_ID: V1SiteVariableSiteId,
        PathValues.V1_SITE_SITE_ID__MAKEDEFAULT: V1SiteSiteIdMakedefault,
        PathValues.V1_SITE_SITE_ID__PUBLISH: V1SiteSiteIdPublish,
        PathValues.V1_SITE_VARIABLE: V1SiteVariable,
        PathValues.V1_SITE_SWITCH: V1SiteSwitch,
        PathValues.V1_SITE_SWITCH_ID: V1SiteSwitchId,
        PathValues.V1_SITE_SITE_ID__UNARCHIVE: V1SiteSiteIdUnarchive,
        PathValues.V1_SITE_SITE_ID__UNPUBLISH: V1SiteSiteIdUnpublish,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES: V1SitesSiteIdRuleengineRules,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID: V1SitesSiteIdRuleengineRulesRuleId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_ACTIONS: V1SitesSiteIdRuleengineActions,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_ACTIONS_ACTION_ID: V1SitesSiteIdRuleengineActionsActionId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID_CONDITION_GROUPS: V1SitesSiteIdRuleengineRulesRuleIdConditionGroups,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID_CONDITION_GROUPS_CONDITION_GROUP_ID: V1SitesSiteIdRuleengineRulesRuleIdConditionGroupsConditionGroupId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID_CONDITION_GROUPS_GROUP_ID: V1SitesSiteIdRuleengineRulesRuleIdConditionGroupsGroupId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS: V1SitesSiteIdRuleengineConditions,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS_CONDITION_ID: V1SitesSiteIdRuleengineConditionsConditionId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS_CONDITION_ID_CONDITION_VALUES: V1SitesSiteIdRuleengineConditionsConditionIdConditionValues,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS_CONDITION_ID_CONDITION_VALUES_VALUE_ID: V1SitesSiteIdRuleengineConditionsConditionIdConditionValuesValueId,
        PathValues.V1_APPCONFIGURATION: V1Appconfiguration,
        PathValues.V1_CONFIGURATION_CONFIG: V1ConfigurationConfig,
        PathValues.V1_CONFIGURATION: V1Configuration,
        PathValues.V1_CONFIGURATION__VALIDATE_COMPANY_EMAIL: V1ConfigurationValidateCompanyEmail,
        PathValues.V1_UPGRADETASK: V1Upgradetask,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_FLUSH: V1CachesProviderProviderFlush,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_FLUSH_GROUP: V1CachesProviderProviderFlushGroup,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_FLUSH_GROUP_ID: V1CachesProviderProviderFlushGroupId,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_KEYS_GROUP: V1CachesProviderProviderKeysGroup,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_OBJECT_GROUP_ID: V1CachesProviderProviderObjectGroupId,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_OBJECTS_GROUP: V1CachesProviderProviderObjectsGroup,
        PathValues.V1_CACHES_PROVIDERS_GROUP: V1CachesProvidersGroup,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_GROUP: V1CachesProviderProviderGroup,
        PathValues.V1_SYSTEM_I18N_LANG_RSRC: V1SystemI18nLangRsrc,
        PathValues.V1_LOGGER: V1Logger,
        PathValues.V1_LOGGER_LOGGER_NAME: V1LoggerLoggerName,
        PathValues.V1_SYSTEMSTATUS_ALIVE: V1SystemStatusAlive,
        PathValues.V1_SYSTEMSTATUS: V1SystemStatus,
        PathValues.V1_PERMISSIONS__BYCONTENT: V1PermissionsBycontent,
        PathValues.V1_PERMISSIONS__BYPERMISSIONTYPE: V1PermissionsBypermissiontype,
        PathValues.V1_REDIS_KEY: V1RedisKey,
        PathValues.V1_REDIS_HASH_KEY: V1RedisHashKey,
        PathValues.V1_REDIS_ECHO_MESSAGE: V1RedisEchoMessage,
        PathValues.V1_REDIS_INCR_KEY: V1RedisIncrKey,
        PathValues.V1_REDIS_PING: V1RedisPing,
        PathValues.V1_REDIS: V1Redis,
        PathValues.V1_REDIS_HASH: V1RedisHash,
        PathValues.V1_ROLES_CHECKUSERROLES_USERID_USER_ID_ROLEIDS_ROLE_IDS: V1RolesCheckuserrolesUseridUserIdRoleidsRoleIds,
        PathValues.V1_ROLES_LAYOUTS: V1RolesLayouts,
        PathValues.V1_ROLES_ROLE_ID_LAYOUTS: V1RolesRoleIdLayouts,
        PathValues.V1_ROLES_ROLEID: V1RolesRoleid,
        PathValues.V1_ROLES: V1Roles,
        PathValues.V1_ROLES_ROLEID_ROLEHIERARCHYANDUSERROLES: V1RolesRoleidRolehierarchyanduserroles,
        PathValues.V1_ROLES__SEARCH: V1RolesSearch,
        PathValues.V1_SYSTEM_RULEENGINE_ACTIONLETS: V1SystemRuleengineActionlets,
        PathValues.V1_SYSTEM_RULEENGINE_CONDITIONLETS: V1SystemRuleengineConditionlets,
        PathValues.V1_LOGS_FILE_NAME__TAIL: V1LogsFileNameTail,
        PathValues.V1_TEMP_BY_URL: V1TempByUrl,
        PathValues.V1_TEMP: V1Temp,
        PathValues.V1_TEMPLATES__ARCHIVE: V1TemplatesArchive,
        PathValues.V1_TEMPLATES_TEMPLATE_ID__COPY: V1TemplatesTemplateIdCopy,
        PathValues.V1_TEMPLATES: V1Templates,
        PathValues.V1_TEMPLATES_TEMPLATE_ID_LIVE: V1TemplatesTemplateIdLive,
        PathValues.V1_TEMPLATES_TEMPLATE_ID_WORKING: V1TemplatesTemplateIdWorking,
        PathValues.V1_TEMPLATES__PUBLISH: V1TemplatesPublish,
        PathValues.V1_TEMPLATES__SAVEPUBLISH: V1TemplatesSavepublish,
        PathValues.V1_TEMPLATES_DRAFT: V1TemplatesDraft,
        PathValues.V1_TEMPLATES__UNARCHIVE: V1TemplatesUnarchive,
        PathValues.V1_TEMPLATES__UNPUBLISH: V1TemplatesUnpublish,
        PathValues.V1_THEMES_ID_ID: V1ThemesIdId,
        PathValues.V1_THEMES: V1Themes,
        PathValues.V1_USERS_FILTER_PARAMS: V1UsersFilterParams,
        PathValues.V1_USERS_LOGINAS: V1UsersLoginas,
        PathValues.V1_USERS_LOGIN_AS_DATA: V1UsersLoginAsData,
        PathValues.V1_USERS_LOGOUTAS: V1UsersLogoutas,
        PathValues.V1_USERS_CURRENT: V1UsersCurrent,
        PathValues.V1_VERSIONABLES_VERSIONABLE_INODE__BRINGBACK: V1VersionablesVersionableInodeBringback,
        PathValues.V1_VERSIONABLES_VERSIONABLE_INODE: V1VersionablesVersionableInode,
        PathValues.V1_VERSIONABLES_VERSIONABLE_INODE_OR_IDENTIFIER: V1VersionablesVersionableInodeOrIdentifier,
        PathValues.VTL_FOLDER: VtlFolder,
        PathValues.VTL_FOLDER_PATH_PARAM: VtlFolderPathParam,
        PathValues.VTL_DYNAMIC_PATH_PARAM: VtlDynamicPathParam,
        PathValues.VTL_DYNAMIC: VtlDynamic,
        PathValues.V1_WORKFLOW_STEPS: V1WorkflowSteps,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_COPY: V1WorkflowSchemesSchemeIdCopy,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID: V1WorkflowActionsActionId,
        PathValues.V1_WORKFLOW_STEPS_STEP_ID_ACTIONS_ACTION_ID: V1WorkflowStepsStepIdActionsActionId,
        PathValues.V1_WORKFLOW_ACTIONLETS_ACTIONLET_ID: V1WorkflowActionletsActionletId,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID: V1WorkflowSchemesSchemeId,
        PathValues.V1_WORKFLOW_STEPS_STEP_ID: V1WorkflowStepsStepId,
        PathValues.V1_WORKFLOW_SYSTEM_ACTIONS_IDENTIFIER: V1WorkflowSystemActionsIdentifier,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_CONDITION: V1WorkflowActionsActionIdCondition,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_EXPORT: V1WorkflowSchemesSchemeIdExport,
        PathValues.V1_WORKFLOW_ACTIONLETS: V1WorkflowActionlets,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_ACTIONLETS: V1WorkflowActionsActionIdActionlets,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_ACTIONS: V1WorkflowSchemesSchemeIdActions,
        PathValues.V1_WORKFLOW_SCHEMES_ACTIONS_SYSTEM_ACTION: V1WorkflowSchemesActionsSystemAction,
        PathValues.V1_WORKFLOW_STEPS_STEP_ID_ACTIONS: V1WorkflowStepsStepIdActions,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEMESCONTENTTYPES_CONTENT_TYPE_ID: V1WorkflowSchemesSchemescontenttypesContentTypeId,
        PathValues.V1_WORKFLOW_CONTENTLET_INODE_ACTIONS: V1WorkflowContentletInodeActions,
        PathValues.V1_WORKFLOW_DEFAULTACTIONS_CONTENTTYPE_CONTENT_TYPE_ID: V1WorkflowDefaultactionsContenttypeContentTypeId,
        PathValues.V1_WORKFLOW_DEFAULTACTIONS_SCHEMES: V1WorkflowDefaultactionsSchemes,
        PathValues.V1_WORKFLOW_INITIALACTIONS_CONTENTTYPE_CONTENT_TYPE_ID: V1WorkflowInitialactionsContenttypeContentTypeId,
        PathValues.V1_WORKFLOW_SCHEMES: V1WorkflowSchemes,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_STEPS: V1WorkflowSchemesSchemeIdSteps,
        PathValues.V1_WORKFLOW_CONTENTTYPES_CONTENT_TYPE_VAR_OR_ID_SYSTEM_ACTIONS: V1WorkflowContenttypesContentTypeVarOrIdSystemActions,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_SYSTEM_ACTIONS: V1WorkflowSchemesSchemeIdSystemActions,
        PathValues.V1_WORKFLOW_ACTIONS_FIRE: V1WorkflowActionsFire,
        PathValues.V1_WORKFLOW_ACTIONS_DEFAULT_FIRE_SYSTEM_ACTION: V1WorkflowActionsDefaultFireSystemAction,
        PathValues.V1_WORKFLOW_ACTIONS_DEFAULT_FIREMULTIPART_SYSTEM_ACTION: V1WorkflowActionsDefaultFiremultipartSystemAction,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_FIRE: V1WorkflowActionsActionIdFire,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_FIREMULTIPART: V1WorkflowActionsActionIdFiremultipart,
        PathValues.V1_WORKFLOW_CONTENTLET_ACTIONS__BULKFIRE: V1WorkflowContentletActionsBulkfire,
        PathValues.V1_WORKFLOW_CONTENTLET_ACTIONS_BULK_FIRE: V1WorkflowContentletActionsBulkFire,
        PathValues.V1_WORKFLOW_CONTENTLET_ACTIONS_BULK: V1WorkflowContentletActionsBulk,
        PathValues.V1_WORKFLOW_SYSTEM_ACTIONS_WORKFLOW_ACTION_ID: V1WorkflowSystemActionsWorkflowActionId,
        PathValues.V1_WORKFLOW_SCHEMES_IMPORT: V1WorkflowSchemesImport,
        PathValues.V1_WORKFLOW_REORDER_STEPS_STEP_ID_ACTIONS_ACTION_ID: V1WorkflowReorderStepsStepIdActionsActionId,
        PathValues.V1_WORKFLOW_REORDER_STEP_STEP_ID_ORDER_ORDER: V1WorkflowReorderStepStepIdOrderOrder,
        PathValues.V1_WORKFLOW_ACTIONS: V1WorkflowActions,
        PathValues.V1_WORKFLOW_SYSTEM_ACTIONS: V1WorkflowSystemActions,
        PathValues.V2_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS: V2ContenttypeTypeIdOrVarNameFields,
        PathValues.V2_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_ID_FIELD_ID: V2ContenttypeTypeIdOrVarNameFieldsIdFieldId,
        PathValues.V2_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_VAR_FIELD_VAR: V2ContenttypeTypeIdOrVarNameFieldsVarFieldVar,
        PathValues.V2_LANGUAGES_LANGUAGE_ID: V2LanguagesLanguageId,
        PathValues.V2_LANGUAGES_ID_LANGUAGEID: V2LanguagesIdLanguageid,
        PathValues.V2_LANGUAGES_LANGUAGE_KEYS: V2LanguagesLanguageKeys,
        PathValues.V2_LANGUAGES_LANGUAGE_TAG: V2LanguagesLanguageTag,
        PathValues.V2_LANGUAGES_I18N: V2LanguagesI18n,
        PathValues.V2_LANGUAGES: V2Languages,
        PathValues.V2_LANGUAGES_LANGUAGE__MAKEDEFAULT: V2LanguagesLanguageMakedefault,
        PathValues.V3_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS: V3ContenttypeTypeIdOrVarNameFields,
        PathValues.V3_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_MOVE: V3ContenttypeTypeIdOrVarNameFieldsMove,
        PathValues.V3_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_ID: V3ContenttypeTypeIdOrVarNameFieldsId,
        PathValues.ES_LAYOUT_PARAMS: EsLayoutParams,
        PathValues.ES_SEARCH: EsSearch,
        PathValues.ES_RAW: EsRaw,
        PathValues.PERSONAS_LAYOUT_PARAMS: PersonasLayoutParams,
        PathValues.PERSONAS_SITES_ID: PersonasSitesId,
        PathValues.APPLICATION_WADL_PATH: ApplicationWadlPath,
        PathValues.APPLICATION_WADL: ApplicationWadl,
    }
)

path_to_api = PathToApi(
    {
        PathValues.V1_DOTSAML_LOGIN_IDP_CONFIG_ID: V1DotsamlLoginIdpConfigId,
        PathValues.V1_DOTSAML_LOGOUT_IDP_CONFIG_ID: V1DotsamlLogoutIdpConfigId,
        PathValues.V1_DOTSAML_METADATA_IDP_CONFIG_ID: V1DotsamlMetadataIdpConfigId,
        PathValues.V1_FIELD_TYPES: V1FieldTypes,
        PathValues.AUDIT_PUBLISHING_GET_BUNDLE_ID: AuditPublishingGetBundleId,
        PathValues.BUNDLE_PUBLISHER_PUBLISH: BundlePublisherPublish,
        PathValues.BUNDLE_ALL: BundleAll,
        PathValues.BUNDLE_ALL_FAIL: BundleAllFail,
        PathValues.BUNDLE_ALL_SUCCESS: BundleAllSuccess,
        PathValues.BUNDLE_IDS: BundleIds,
        PathValues.BUNDLE_OLDERTHAN_OLDER_THAN: BundleOlderthanOlderThan,
        PathValues.BUNDLE_DELETEENVIRONMENTPUSHHISTORY_PARAMS: BundleDeleteenvironmentpushhistoryParams,
        PathValues.BUNDLE_DELETEPUSHHISTORY_PARAMS: BundleDeletepushhistoryParams,
        PathValues.BUNDLE__DOWNLOAD_BUNDLE_ID: BundleDownloadBundleId,
        PathValues.BUNDLE_BUNDLE_ID_MANIFEST: BundleBundleIdManifest,
        PathValues.BUNDLE__GENERATE: BundleGenerate,
        PathValues.BUNDLE_BUNDLE_ID_ASSETS: BundleBundleIdAssets,
        PathValues.BUNDLE_GETUNSENDBUNDLES_PARAMS: BundleGetunsendbundlesParams,
        PathValues.BUNDLE_UPDATEBUNDLE_PARAMS: BundleUpdatebundleParams,
        PathValues.BUNDLE: Bundle,
        PathValues.BUNDLE_SYNC: BundleSync,
        PathValues.CONFIG_DELETE_ENDPOINT: ConfigDeleteEndpoint,
        PathValues.CONFIG_DELETE_ENVIRONMENT: ConfigDeleteEnvironment,
        PathValues.CONFIG_REGENERATE_KEY: ConfigRegenerateKey,
        PathValues.CONFIG_SAVE_COMPANY_AUTH_TYPE_INFO: ConfigSaveCompanyAuthTypeInfo,
        PathValues.CONFIG_SAVE_COMPANY_BASIC_INFO: ConfigSaveCompanyBasicInfo,
        PathValues.CONFIG_SAVE_COMPANY_LOCALE_INFO: ConfigSaveCompanyLocaleInfo,
        PathValues.CONFIG_SAVE_COMPANY_LOGO: ConfigSaveCompanyLogo,
        PathValues.CLUSTER_GET_ESCONFIG_PROPERTIES_PARAMS: ClusterGetESConfigPropertiesParams,
        PathValues.CLUSTER_LICENSE_REPO_STATUS: ClusterLicenseRepoStatus,
        PathValues.CLUSTER_GET_NODES_STATUS_PARAMS: ClusterGetNodesStatusParams,
        PathValues.CLUSTER_REMOVE_PARAMS: ClusterRemoveParams,
        PathValues.CLUSTER_TEST: ClusterTest,
        PathValues.CONTENT_CAN_LOCK_PARAMS: ContentCanLockParams,
        PathValues.CONTENT_PARAMS: ContentParams,
        PathValues.CONTENT_INDEXCOUNT_QUERY: ContentIndexcountQuery,
        PathValues.CONTENT_INDEXSEARCH_QUERY_SORTBY_SORTBY_LIMIT_LIMIT_OFFSET_OFFSET: ContentIndexsearchQuerySortbySortbyLimitLimitOffsetOffset,
        PathValues.CONTENT_LOCK_PARAMS: ContentLockParams,
        PathValues.CONTENT__SEARCH: ContentSearch,
        PathValues.CONTENT_UNLOCK_PARAMS: ContentUnlockParams,
        PathValues.ENVIRONMENT_LOADENVIRONMENTS_PARAMS: EnvironmentLoadenvironmentsParams,
        PathValues.INTEGRITY_CHECKINTEGRITY_PARAMS: IntegrityCheckintegrityParams,
        PathValues.INTEGRITY_CHECK_INTEGRITY_PROCESS_STATUS_PARAMS: IntegrityCheckIntegrityProcessStatusParams,
        PathValues.INTEGRITY_DISCARDCONFLICTS_PARAMS: IntegrityDiscardconflictsParams,
        PathValues.INTEGRITY_FIXCONFLICTS_PARAMS: IntegrityFixconflictsParams,
        PathValues.INTEGRITY__FIXCONFLICTSFROMREMOTE: IntegrityFixconflictsfromremote,
        PathValues.INTEGRITY__GENERATEINTEGRITYDATA: IntegrityGenerateintegritydata,
        PathValues.INTEGRITY_REQUEST_ID_INTEGRITY_DATA: IntegrityRequestIdIntegrityData,
        PathValues.INTEGRITY_GET_INTEGRITY_RESULT_PARAMS: IntegrityGetIntegrityResultParams,
        PathValues.PORTLET_LAYOUT_PARAMS: PortletLayoutParams,
        PathValues.PORTLET_PARAMS: PortletParams,
        PathValues.LICENSE_APPLY_LICENSE: LicenseApplyLicense,
        PathValues.LICENSE_DELETE_PARAMS: LicenseDeleteParams,
        PathValues.LICENSE_FREE_PARAMS: LicenseFreeParams,
        PathValues.LICENSE_ALL_PARAMS: LicenseAllParams,
        PathValues.LICENSE_PICK_PARAMS: LicensePickParams,
        PathValues.LICENSE_UPLOAD_PARAMS: LicenseUploadParams,
        PathValues.LICENSE_REQUEST_CODE_PARAMS: LicenseRequestCodeParams,
        PathValues.LICENSE_RESET_LICENSE_PARAMS: LicenseResetLicenseParams,
        PathValues.OSGI_GET_INSTALLED_BUNDLES_PARAMS: OsgiGetInstalledBundlesParams,
        PathValues.OSGI__PROCESS_EXPORTS_BUNDLE: OsgiProcessExportsBundle,
        PathValues.OSGI: Osgi,
        PathValues.V1_PUBLISHQUEUE: V1Publishqueue,
        PathValues.RESTEXAMPLE_LAYOUT_PARAMS: RestexampleLayoutParams,
        PathValues.RESTEXAMPLE_TEST_PARAMS: RestexampleTestParams,
        PathValues.ROLE_LOADBYID_PARAMS: RoleLoadbyidParams,
        PathValues.ROLE_LOADBYNAME_PARAMS: RoleLoadbynameParams,
        PathValues.ROLE_LOADCHILDREN_PARAMS: RoleLoadchildrenParams,
        PathValues.RULESENGINE_LAYOUT_PARAMS: RulesengineLayoutParams,
        PathValues.STRUCTURE_PATH: StructurePath,
        PathValues.V1_TAGS: V1Tags,
        PathValues.V1_TAGS_TAG_ID: V1TagsTagId,
        PathValues.V1_TAGS_INODE_INODE: V1TagsInodeInode,
        PathValues.V1_TAGS_NAME_OR_ID: V1TagsNameOrId,
        PathValues.V1_TAGS_USER_USER_ID: V1TagsUserUserId,
        PathValues.V1_TAGS_IMPORT: V1TagsImport,
        PathValues.V1_TAGS_TAG_NAME_OR_ID_INODE_INODE: V1TagsTagNameOrIdInodeInode,
        PathValues.TEST_RESOURCE_TEST_GET_PARAMS: TestResourceTestGetParams,
        PathValues.TEST_RESOURCE_TEST_POST: TestResourceTestPost,
        PathValues.USER_GETLOGGEDINUSER_PARAMS: UserGetloggedinuserParams,
        PathValues.UTIL_ENCODE_QUERY_PARAM_VALUE_PARAMS: UtilEncodeQueryParamValueParams,
        PathValues.WIDGET_PARAMS: WidgetParams,
        PathValues.V1_APPS: V1Apps,
        PathValues.V1_APPS_KEY_SITE_ID: V1AppsKeySiteId,
        PathValues.V1_APPS_KEY: V1AppsKey,
        PathValues.V1_APPS_EXPORT: V1AppsExport,
        PathValues.V1_APPS_IMPORT: V1AppsImport,
        PathValues.V1_APITOKEN_TOKEN_ID: V1ApitokenTokenId,
        PathValues.V1_APITOKEN_USER_ID_TOKENS: V1ApitokenUserIdTokens,
        PathValues.V1_APITOKEN_TOKEN_ID_JWT: V1ApitokenTokenIdJwt,
        PathValues.V1_APITOKEN_REMOTE: V1ApitokenRemote,
        PathValues.V1_APITOKEN: V1Apitoken,
        PathValues.V1_APITOKEN_TOKEN_ID_REVOKE: V1ApitokenTokenIdRevoke,
        PathValues.V1_APITOKEN_USERS_USERID_REVOKE: V1ApitokenUsersUseridRevoke,
        PathValues.V1_APITOKEN_USERS_REVOKE: V1ApitokenUsersRevoke,
        PathValues.V1_AUTHENTICATION: V1Authentication,
        PathValues.V1_AUTHENTICATION_LOG_IN_USER: V1AuthenticationLogInUser,
        PathValues.V1_AUTHENTICATION_APITOKEN: V1AuthenticationApiToken,
        PathValues.V1_FORGOTPASSWORD: V1Forgotpassword,
        PathValues.V1_LOGINFORM: V1Loginform,
        PathValues.V1_LOGOUT: V1Logout,
        PathValues.V1_CHANGE_PASSWORD: V1ChangePassword,
        PathValues.V1_BROWSER: V1Browser,
        PathValues.V1_BROWSER_SELECTEDFOLDER: V1BrowserSelectedfolder,
        PathValues.V1_BROWSERTREE_SITENAME_SITENAME_URI: V1BrowsertreeSitenameSitenameUri,
        PathValues.V1_BROWSERTREE_SITENAME_SITENAME_URI_URI: V1BrowsertreeSitenameSitenameUriUri,
        PathValues.V1_CATEGORIES: V1Categories,
        PathValues.V1_CATEGORIES__EXPORT: V1CategoriesExport,
        PathValues.V1_CATEGORIES_ID_OR_KEY: V1CategoriesIdOrKey,
        PathValues.V1_CATEGORIES_CHILDREN: V1CategoriesChildren,
        PathValues.V1_CATEGORIES__IMPORT: V1CategoriesImport,
        PathValues.V1_CATEGORIES__SORT: V1CategoriesSort,
        PathValues.V1_CONTAINERS__ARCHIVE: V1ContainersArchive,
        PathValues.V1_CONTAINERS__BULKARCHIVE: V1ContainersBulkarchive,
        PathValues.V1_CONTAINERS__BULKDELETE: V1ContainersBulkdelete,
        PathValues.V1_CONTAINERS__BULKPUBLISH: V1ContainersBulkpublish,
        PathValues.V1_CONTAINERS__BULKUNARCHIVE: V1ContainersBulkunarchive,
        PathValues.V1_CONTAINERS__BULKUNPUBLISH: V1ContainersBulkunpublish,
        PathValues.V1_CONTAINERS_CONTAINER_ID_CONTENT_CONTENTLET_ID: V1ContainersContainerIdContentContentletId,
        PathValues.V1_CONTAINERS_CONTENT_CONTENTLET_ID: V1ContainersContentContentletId,
        PathValues.V1_CONTAINERS_CONTAINER_ID_FORM_FORM_ID: V1ContainersContainerIdFormFormId,
        PathValues.V1_CONTAINERS_FORM_FORM_ID: V1ContainersFormFormId,
        PathValues.V1_CONTAINERS_ID__COPY: V1ContainersIdCopy,
        PathValues.V1_CONTAINERS: V1Containers,
        PathValues.V1_CONTAINERS_LIVE: V1ContainersLive,
        PathValues.V1_CONTAINERS_WORKING: V1ContainersWorking,
        PathValues.V1_CONTAINERS__PUBLISH: V1ContainersPublish,
        PathValues.V1_CONTAINERS_DELETE_CONTAINER_ID_CONTENT_CONTENTLET_ID_UID_UID: V1ContainersDeleteContainerIdContentContentletIdUidUid,
        PathValues.V1_CONTAINERS__UNARCHIVE: V1ContainersUnarchive,
        PathValues.V1_CONTAINERS__UNPUBLISH: V1ContainersUnpublish,
        PathValues.V1_CONTENTRELATIONSHIPS_PARAMS: V1ContentrelationshipsParams,
        PathValues.V1_CONTENT__CANLOCK_INODE_OR_IDENTIFIER: V1ContentCanlockInodeOrIdentifier,
        PathValues.V1_CONTENT_INODE_OR_IDENTIFIER: V1ContentInodeOrIdentifier,
        PathValues.V1_CONTENT_RELATED: V1ContentRelated,
        PathValues.V1_CONTENT_VERSIONS_INODE: V1ContentVersionsInode,
        PathValues.V1_CONTENT_VERSIONS: V1ContentVersions,
        PathValues.V1_CONTENT_RESOURCELINKS_FIELD_FIELD: V1ContentResourcelinksFieldField,
        PathValues.V1_CONTENT_RESOURCELINKS: V1ContentResourcelinks,
        PathValues.V1_CONTENTTYPE_BASE_VARIABLE_NAME__COPY: V1ContenttypeBaseVariableNameCopy,
        PathValues.V1_CONTENTTYPE: V1Contenttype,
        PathValues.V1_CONTENTTYPE_ID_ID_OR_VAR: V1ContenttypeIdIdOrVar,
        PathValues.V1_CONTENTTYPE__FILTER: V1ContenttypeFilter,
        PathValues.V1_CONTENTTYPE_BASETYPES: V1ContenttypeBasetypes,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS: V1ContenttypeTypeIdFields,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_ID_FIELD_ID: V1ContenttypeTypeIdFieldsIdFieldId,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_VAR_FIELD_VAR: V1ContenttypeTypeIdFieldsVarFieldVar,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_ID_FIELD_ID_VARIABLES: V1ContenttypeTypeIdFieldsIdFieldIdVariables,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_VAR_FIELD_VAR_VARIABLES: V1ContenttypeTypeIdFieldsVarFieldVarVariables,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_ID_FIELD_ID_VARIABLES_ID_FIELD_VAR_ID: V1ContenttypeTypeIdFieldsIdFieldIdVariablesIdFieldVarId,
        PathValues.V1_CONTENTTYPE_TYPE_ID_FIELDS_VAR_FIELD_VAR_VARIABLES_ID_FIELD_VAR_ID: V1ContenttypeTypeIdFieldsVarFieldVarVariablesIdFieldVarId,
        PathValues.WS_V1_SYSTEM_EVENTS: WsV1SystemEvents,
        PathValues.WS_V1_SYSTEM_SYNCEVENTS: WsV1SystemSyncevents,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_VARIANTS: V1ExperimentsExperimentIdVariants,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID__ARCHIVE: V1ExperimentsExperimentIdArchive,
        PathValues.V1_EXPERIMENTS: V1Experiments,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID: V1ExperimentsExperimentId,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_GOALS_PRIMARY: V1ExperimentsExperimentIdGoalsPrimary,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_TARGETING_CONDITIONS_ID: V1ExperimentsExperimentIdTargetingConditionsId,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID_VARIANTS_NAME: V1ExperimentsExperimentIdVariantsName,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID__END: V1ExperimentsExperimentIdEnd,
        PathValues.V1_EXPERIMENTS_ID: V1ExperimentsId,
        PathValues.V1_EXPERIMENTS_IS_USER_INCLUDED: V1ExperimentsIsUserIncluded,
        PathValues.V1_EXPERIMENTS_EXPERIMENT_ID__START: V1ExperimentsExperimentIdStart,
        PathValues.V1_CONTENT_FILEASSETS_INODE_RESOURCELINK: V1ContentFileassetsInodeResourcelink,
        PathValues.V1_FOLDER_CREATEFOLDERS_SITE_NAME: V1FolderCreatefoldersSiteName,
        PathValues.V1_FOLDER_SITE_NAME: V1FolderSiteName,
        PathValues.V1_FOLDER_FOLDER_ID: V1FolderFolderId,
        PathValues.V1_FOLDER_BY_PATH: V1FolderByPath,
        PathValues.V1_FOLDER_SITE_ID_SITE_ID_PATH_PATH: V1FolderSiteIdSiteIdPathPath,
        PathValues.V1_FOLDER_SITENAME_SITE_NAME_URI_URI: V1FolderSitenameSiteNameUriUri,
        PathValues.V1_FOLDER_ID_FILEBROWSERSELECTED: V1FolderIdFileBrowserSelected,
        PathValues.V1_FORM_ID_OR_VAR_SUCCESS_CALLBACK: V1FormIdOrVarSuccessCallback,
        PathValues.V1_ESINDEX_ACTIVATE_PARAMS: V1EsindexActivateParams,
        PathValues.V1_ESINDEX_CLEAR_PARAMS: V1EsindexClearParams,
        PathValues.V1_ESINDEX_CLOSE_PARAMS: V1EsindexCloseParams,
        PathValues.V1_ESINDEX_CREATE_PARAMS: V1EsindexCreateParams,
        PathValues.V1_ESINDEX_DEACTIVATE_PARAMS: V1EsindexDeactivateParams,
        PathValues.V1_ESINDEX_FAILED: V1EsindexFailed,
        PathValues.V1_ESINDEX_INDEX_NAME: V1EsindexIndexName,
        PathValues.V1_ESINDEX_CACHE: V1EsindexCache,
        PathValues.V1_ESINDEX_ACTIVE_PARAMS: V1EsindexActiveParams,
        PathValues.V1_ESINDEX_CLUSTER: V1EsindexCluster,
        PathValues.V1_ESINDEX: V1Esindex,
        PathValues.V1_ESINDEX_REINDEX: V1EsindexReindex,
        PathValues.V1_ESINDEX_INDEXLIST_PARAMS: V1EsindexIndexlistParams,
        PathValues.V1_ESINDEX_OPEN_PARAMS: V1EsindexOpenParams,
        PathValues.V1_ESINDEX_OPTIMIZE: V1EsindexOptimize,
        PathValues.V1_LANGUAGES_I18N: V1LanguagesI18n,
        PathValues.V1_LANGUAGES: V1Languages,
        PathValues.V1_JVM: V1Jvm,
        PathValues.V1_MAINTENANCE__DOWNLOAD_ASSETS: V1MaintenanceDownloadAssets,
        PathValues.V1_MAINTENANCE__DOWNLOAD_DB: V1MaintenanceDownloadDb,
        PathValues.V1_MAINTENANCE__DOWNLOAD_LOG_FILE_NAME: V1MaintenanceDownloadLogFileName,
        PathValues.V1_MAINTENANCE__DOWNLOAD_STARTER: V1MaintenanceDownloadStarter,
        PathValues.V1_MAINTENANCE__DOWNLOAD_STARTER_WITH_ASSETS: V1MaintenanceDownloadStarterWithAssets,
        PathValues.V1_MAINTENANCE__PG_DUMP_AVAILABLE: V1MaintenancePgDumpAvailable,
        PathValues.V1_MAINTENANCE__SHUTDOWN: V1MaintenanceShutdown,
        PathValues.V1_MENU: V1Menu,
        PathValues.V1_NOTIFICATION_DELETE: V1NotificationDelete,
        PathValues.V1_NOTIFICATION_ID_ID: V1NotificationIdId,
        PathValues.V1_NOTIFICATION_GET_NEW_NOTIFICATIONS_COUNT: V1NotificationGetNewNotificationsCount,
        PathValues.V1_NOTIFICATION_GET_NOTIFICATIONS_PARAMS: V1NotificationGetNotificationsParams,
        PathValues.V1_NOTIFICATION_MARK_AS_READ: V1NotificationMarkAsRead,
        PathValues.V1_NAV_URI: V1NavUri,
        PathValues.V1_PAGE_PAGE_ID_CONTENT: V1PagePageIdContent,
        PathValues.V1_PAGE_COPY_CONTENT: V1PageCopyContent,
        PathValues.V1_PAGE_PAGE_ID__DEEPCOPY: V1PagePageIdDeepcopy,
        PathValues.V1_PAGE_PAGE_ID_CONTENT_TREE: V1PagePageIdContentTree,
        PathValues.V1_PAGE_PAGE_ID_RENDER_VERSIONS: V1PagePageIdRenderVersions,
        PathValues.V1_PAGE_PAGE_ID_PERSONAS: V1PagePageIdPersonas,
        PathValues.V1_PAGE_JSON_URI: V1PageJsonUri,
        PathValues.V1_PAGE_RENDER_URI: V1PageRenderUri,
        PathValues.V1_PAGE_RENDER_HTML_URI: V1PageRenderHTMLUri,
        PathValues.V1_PAGE_LAYOUT: V1PageLayout,
        PathValues.V1_PAGE_PAGE_ID_LAYOUT: V1PagePageIdLayout,
        PathValues.V1_PAGE_SEARCH: V1PageSearch,
        PathValues.V1_PERSONALIZATION_PAGEPERSONAS: V1PersonalizationPagepersonas,
        PathValues.V1_PERSONALIZATION_PAGEPERSONAS_PAGE_PAGE_ID_PERSONALIZATION_PERSONALIZATION: V1PersonalizationPagepersonasPagePageIdPersonalizationPersonalization,
        PathValues.V1_PERSONAS: V1Personas,
        PathValues.V1_PERSONAS_ID: V1PersonasId,
        PathValues.V1_PORTLET_CUSTOM_PORTLET_ID__ADDTOLAYOUT_LAYOUT_ID: V1PortletCustomPortletIdAddtolayoutLayoutId,
        PathValues.V1_PORTLET_CUSTOM: V1PortletCustom,
        PathValues.V1_PORTLET_CUSTOM_PORTLET_ID: V1PortletCustomPortletId,
        PathValues.V1_PORTLET_PORTLET_ID_PORTLET_ID: V1PortletPortletIdPortletId,
        PathValues.V1_PORTLET_PORTLET_ID_PORTLET_ID_ROLE_ID_ROLE_ID: V1PortletPortletIdPortletIdRoleIdRoleId,
        PathValues.V1_PORTLET_PORTLET_ID__DOESUSERHAVEACCESS: V1PortletPortletIdDoesuserhaveaccess,
        PathValues.V1_PORTLET_PORTLET_ID: V1PortletPortletId,
        PathValues.V1_PORTLET__ACTIONURL_CONTENT_TYPE_VARIABLE: V1PortletActionurlContentTypeVariable,
        PathValues.V1_TOOLGROUPS_LAYOUT_ID__ADDTOUSER: V1ToolgroupsLayoutIdAddtouser,
        PathValues.V1_TOOLGROUPS_LAYOUT_ID__REMOVEFROMUSER: V1ToolgroupsLayoutIdRemovefromuser,
        PathValues.V1_TOOLGROUPS_LAYOUT_ID__USER_HAS_LAYOUT: V1ToolgroupsLayoutIdUserHasLayout,
        PathValues.V1_PUSHPUBLISH_FILTERS_FILTER_KEY: V1PushpublishFiltersFilterKey,
        PathValues.V1_PUSHPUBLISH_FILTERS: V1PushpublishFilters,
        PathValues.V1_RELATIONSHIPS_CARDINALITIES: V1RelationshipsCardinalities,
        PathValues.V1_RELATIONSHIPS: V1Relationships,
        PathValues.V1_SITE_SITE_ID__ARCHIVE: V1SiteSiteIdArchive,
        PathValues.V1_SITE__COPY: V1SiteCopy,
        PathValues.V1_SITE: V1Site,
        PathValues.V1_SITE_CURRENT_SITE: V1SiteCurrentSite,
        PathValues.V1_SITE_DEFAULT_SITE: V1SiteDefaultSite,
        PathValues.V1_SITE_SITE_ID: V1SiteSiteId,
        PathValues.V1_SITE_THUMBNAILS: V1SiteThumbnails,
        PathValues.V1_SITE__BYNAME: V1SiteByname,
        PathValues.V1_SITE_SITE_ID_SETUP_PROGRESS: V1SiteSiteIdSetupProgress,
        PathValues.V1_SITE_VARIABLE_SITE_ID: V1SiteVariableSiteId,
        PathValues.V1_SITE_SITE_ID__MAKEDEFAULT: V1SiteSiteIdMakedefault,
        PathValues.V1_SITE_SITE_ID__PUBLISH: V1SiteSiteIdPublish,
        PathValues.V1_SITE_VARIABLE: V1SiteVariable,
        PathValues.V1_SITE_SWITCH: V1SiteSwitch,
        PathValues.V1_SITE_SWITCH_ID: V1SiteSwitchId,
        PathValues.V1_SITE_SITE_ID__UNARCHIVE: V1SiteSiteIdUnarchive,
        PathValues.V1_SITE_SITE_ID__UNPUBLISH: V1SiteSiteIdUnpublish,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES: V1SitesSiteIdRuleengineRules,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID: V1SitesSiteIdRuleengineRulesRuleId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_ACTIONS: V1SitesSiteIdRuleengineActions,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_ACTIONS_ACTION_ID: V1SitesSiteIdRuleengineActionsActionId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID_CONDITION_GROUPS: V1SitesSiteIdRuleengineRulesRuleIdConditionGroups,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID_CONDITION_GROUPS_CONDITION_GROUP_ID: V1SitesSiteIdRuleengineRulesRuleIdConditionGroupsConditionGroupId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_RULES_RULE_ID_CONDITION_GROUPS_GROUP_ID: V1SitesSiteIdRuleengineRulesRuleIdConditionGroupsGroupId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS: V1SitesSiteIdRuleengineConditions,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS_CONDITION_ID: V1SitesSiteIdRuleengineConditionsConditionId,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS_CONDITION_ID_CONDITION_VALUES: V1SitesSiteIdRuleengineConditionsConditionIdConditionValues,
        PathValues.V1_SITES_SITE_ID_RULEENGINE_CONDITIONS_CONDITION_ID_CONDITION_VALUES_VALUE_ID: V1SitesSiteIdRuleengineConditionsConditionIdConditionValuesValueId,
        PathValues.V1_APPCONFIGURATION: V1Appconfiguration,
        PathValues.V1_CONFIGURATION_CONFIG: V1ConfigurationConfig,
        PathValues.V1_CONFIGURATION: V1Configuration,
        PathValues.V1_CONFIGURATION__VALIDATE_COMPANY_EMAIL: V1ConfigurationValidateCompanyEmail,
        PathValues.V1_UPGRADETASK: V1Upgradetask,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_FLUSH: V1CachesProviderProviderFlush,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_FLUSH_GROUP: V1CachesProviderProviderFlushGroup,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_FLUSH_GROUP_ID: V1CachesProviderProviderFlushGroupId,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_KEYS_GROUP: V1CachesProviderProviderKeysGroup,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_OBJECT_GROUP_ID: V1CachesProviderProviderObjectGroupId,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_OBJECTS_GROUP: V1CachesProviderProviderObjectsGroup,
        PathValues.V1_CACHES_PROVIDERS_GROUP: V1CachesProvidersGroup,
        PathValues.V1_CACHES_PROVIDER_PROVIDER_GROUP: V1CachesProviderProviderGroup,
        PathValues.V1_SYSTEM_I18N_LANG_RSRC: V1SystemI18nLangRsrc,
        PathValues.V1_LOGGER: V1Logger,
        PathValues.V1_LOGGER_LOGGER_NAME: V1LoggerLoggerName,
        PathValues.V1_SYSTEMSTATUS_ALIVE: V1SystemStatusAlive,
        PathValues.V1_SYSTEMSTATUS: V1SystemStatus,
        PathValues.V1_PERMISSIONS__BYCONTENT: V1PermissionsBycontent,
        PathValues.V1_PERMISSIONS__BYPERMISSIONTYPE: V1PermissionsBypermissiontype,
        PathValues.V1_REDIS_KEY: V1RedisKey,
        PathValues.V1_REDIS_HASH_KEY: V1RedisHashKey,
        PathValues.V1_REDIS_ECHO_MESSAGE: V1RedisEchoMessage,
        PathValues.V1_REDIS_INCR_KEY: V1RedisIncrKey,
        PathValues.V1_REDIS_PING: V1RedisPing,
        PathValues.V1_REDIS: V1Redis,
        PathValues.V1_REDIS_HASH: V1RedisHash,
        PathValues.V1_ROLES_CHECKUSERROLES_USERID_USER_ID_ROLEIDS_ROLE_IDS: V1RolesCheckuserrolesUseridUserIdRoleidsRoleIds,
        PathValues.V1_ROLES_LAYOUTS: V1RolesLayouts,
        PathValues.V1_ROLES_ROLE_ID_LAYOUTS: V1RolesRoleIdLayouts,
        PathValues.V1_ROLES_ROLEID: V1RolesRoleid,
        PathValues.V1_ROLES: V1Roles,
        PathValues.V1_ROLES_ROLEID_ROLEHIERARCHYANDUSERROLES: V1RolesRoleidRolehierarchyanduserroles,
        PathValues.V1_ROLES__SEARCH: V1RolesSearch,
        PathValues.V1_SYSTEM_RULEENGINE_ACTIONLETS: V1SystemRuleengineActionlets,
        PathValues.V1_SYSTEM_RULEENGINE_CONDITIONLETS: V1SystemRuleengineConditionlets,
        PathValues.V1_LOGS_FILE_NAME__TAIL: V1LogsFileNameTail,
        PathValues.V1_TEMP_BY_URL: V1TempByUrl,
        PathValues.V1_TEMP: V1Temp,
        PathValues.V1_TEMPLATES__ARCHIVE: V1TemplatesArchive,
        PathValues.V1_TEMPLATES_TEMPLATE_ID__COPY: V1TemplatesTemplateIdCopy,
        PathValues.V1_TEMPLATES: V1Templates,
        PathValues.V1_TEMPLATES_TEMPLATE_ID_LIVE: V1TemplatesTemplateIdLive,
        PathValues.V1_TEMPLATES_TEMPLATE_ID_WORKING: V1TemplatesTemplateIdWorking,
        PathValues.V1_TEMPLATES__PUBLISH: V1TemplatesPublish,
        PathValues.V1_TEMPLATES__SAVEPUBLISH: V1TemplatesSavepublish,
        PathValues.V1_TEMPLATES_DRAFT: V1TemplatesDraft,
        PathValues.V1_TEMPLATES__UNARCHIVE: V1TemplatesUnarchive,
        PathValues.V1_TEMPLATES__UNPUBLISH: V1TemplatesUnpublish,
        PathValues.V1_THEMES_ID_ID: V1ThemesIdId,
        PathValues.V1_THEMES: V1Themes,
        PathValues.V1_USERS_FILTER_PARAMS: V1UsersFilterParams,
        PathValues.V1_USERS_LOGINAS: V1UsersLoginas,
        PathValues.V1_USERS_LOGIN_AS_DATA: V1UsersLoginAsData,
        PathValues.V1_USERS_LOGOUTAS: V1UsersLogoutas,
        PathValues.V1_USERS_CURRENT: V1UsersCurrent,
        PathValues.V1_VERSIONABLES_VERSIONABLE_INODE__BRINGBACK: V1VersionablesVersionableInodeBringback,
        PathValues.V1_VERSIONABLES_VERSIONABLE_INODE: V1VersionablesVersionableInode,
        PathValues.V1_VERSIONABLES_VERSIONABLE_INODE_OR_IDENTIFIER: V1VersionablesVersionableInodeOrIdentifier,
        PathValues.VTL_FOLDER: VtlFolder,
        PathValues.VTL_FOLDER_PATH_PARAM: VtlFolderPathParam,
        PathValues.VTL_DYNAMIC_PATH_PARAM: VtlDynamicPathParam,
        PathValues.VTL_DYNAMIC: VtlDynamic,
        PathValues.V1_WORKFLOW_STEPS: V1WorkflowSteps,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_COPY: V1WorkflowSchemesSchemeIdCopy,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID: V1WorkflowActionsActionId,
        PathValues.V1_WORKFLOW_STEPS_STEP_ID_ACTIONS_ACTION_ID: V1WorkflowStepsStepIdActionsActionId,
        PathValues.V1_WORKFLOW_ACTIONLETS_ACTIONLET_ID: V1WorkflowActionletsActionletId,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID: V1WorkflowSchemesSchemeId,
        PathValues.V1_WORKFLOW_STEPS_STEP_ID: V1WorkflowStepsStepId,
        PathValues.V1_WORKFLOW_SYSTEM_ACTIONS_IDENTIFIER: V1WorkflowSystemActionsIdentifier,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_CONDITION: V1WorkflowActionsActionIdCondition,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_EXPORT: V1WorkflowSchemesSchemeIdExport,
        PathValues.V1_WORKFLOW_ACTIONLETS: V1WorkflowActionlets,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_ACTIONLETS: V1WorkflowActionsActionIdActionlets,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_ACTIONS: V1WorkflowSchemesSchemeIdActions,
        PathValues.V1_WORKFLOW_SCHEMES_ACTIONS_SYSTEM_ACTION: V1WorkflowSchemesActionsSystemAction,
        PathValues.V1_WORKFLOW_STEPS_STEP_ID_ACTIONS: V1WorkflowStepsStepIdActions,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEMESCONTENTTYPES_CONTENT_TYPE_ID: V1WorkflowSchemesSchemescontenttypesContentTypeId,
        PathValues.V1_WORKFLOW_CONTENTLET_INODE_ACTIONS: V1WorkflowContentletInodeActions,
        PathValues.V1_WORKFLOW_DEFAULTACTIONS_CONTENTTYPE_CONTENT_TYPE_ID: V1WorkflowDefaultactionsContenttypeContentTypeId,
        PathValues.V1_WORKFLOW_DEFAULTACTIONS_SCHEMES: V1WorkflowDefaultactionsSchemes,
        PathValues.V1_WORKFLOW_INITIALACTIONS_CONTENTTYPE_CONTENT_TYPE_ID: V1WorkflowInitialactionsContenttypeContentTypeId,
        PathValues.V1_WORKFLOW_SCHEMES: V1WorkflowSchemes,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_STEPS: V1WorkflowSchemesSchemeIdSteps,
        PathValues.V1_WORKFLOW_CONTENTTYPES_CONTENT_TYPE_VAR_OR_ID_SYSTEM_ACTIONS: V1WorkflowContenttypesContentTypeVarOrIdSystemActions,
        PathValues.V1_WORKFLOW_SCHEMES_SCHEME_ID_SYSTEM_ACTIONS: V1WorkflowSchemesSchemeIdSystemActions,
        PathValues.V1_WORKFLOW_ACTIONS_FIRE: V1WorkflowActionsFire,
        PathValues.V1_WORKFLOW_ACTIONS_DEFAULT_FIRE_SYSTEM_ACTION: V1WorkflowActionsDefaultFireSystemAction,
        PathValues.V1_WORKFLOW_ACTIONS_DEFAULT_FIREMULTIPART_SYSTEM_ACTION: V1WorkflowActionsDefaultFiremultipartSystemAction,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_FIRE: V1WorkflowActionsActionIdFire,
        PathValues.V1_WORKFLOW_ACTIONS_ACTION_ID_FIREMULTIPART: V1WorkflowActionsActionIdFiremultipart,
        PathValues.V1_WORKFLOW_CONTENTLET_ACTIONS__BULKFIRE: V1WorkflowContentletActionsBulkfire,
        PathValues.V1_WORKFLOW_CONTENTLET_ACTIONS_BULK_FIRE: V1WorkflowContentletActionsBulkFire,
        PathValues.V1_WORKFLOW_CONTENTLET_ACTIONS_BULK: V1WorkflowContentletActionsBulk,
        PathValues.V1_WORKFLOW_SYSTEM_ACTIONS_WORKFLOW_ACTION_ID: V1WorkflowSystemActionsWorkflowActionId,
        PathValues.V1_WORKFLOW_SCHEMES_IMPORT: V1WorkflowSchemesImport,
        PathValues.V1_WORKFLOW_REORDER_STEPS_STEP_ID_ACTIONS_ACTION_ID: V1WorkflowReorderStepsStepIdActionsActionId,
        PathValues.V1_WORKFLOW_REORDER_STEP_STEP_ID_ORDER_ORDER: V1WorkflowReorderStepStepIdOrderOrder,
        PathValues.V1_WORKFLOW_ACTIONS: V1WorkflowActions,
        PathValues.V1_WORKFLOW_SYSTEM_ACTIONS: V1WorkflowSystemActions,
        PathValues.V2_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS: V2ContenttypeTypeIdOrVarNameFields,
        PathValues.V2_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_ID_FIELD_ID: V2ContenttypeTypeIdOrVarNameFieldsIdFieldId,
        PathValues.V2_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_VAR_FIELD_VAR: V2ContenttypeTypeIdOrVarNameFieldsVarFieldVar,
        PathValues.V2_LANGUAGES_LANGUAGE_ID: V2LanguagesLanguageId,
        PathValues.V2_LANGUAGES_ID_LANGUAGEID: V2LanguagesIdLanguageid,
        PathValues.V2_LANGUAGES_LANGUAGE_KEYS: V2LanguagesLanguageKeys,
        PathValues.V2_LANGUAGES_LANGUAGE_TAG: V2LanguagesLanguageTag,
        PathValues.V2_LANGUAGES_I18N: V2LanguagesI18n,
        PathValues.V2_LANGUAGES: V2Languages,
        PathValues.V2_LANGUAGES_LANGUAGE__MAKEDEFAULT: V2LanguagesLanguageMakedefault,
        PathValues.V3_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS: V3ContenttypeTypeIdOrVarNameFields,
        PathValues.V3_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_MOVE: V3ContenttypeTypeIdOrVarNameFieldsMove,
        PathValues.V3_CONTENTTYPE_TYPE_ID_OR_VAR_NAME_FIELDS_ID: V3ContenttypeTypeIdOrVarNameFieldsId,
        PathValues.ES_LAYOUT_PARAMS: EsLayoutParams,
        PathValues.ES_SEARCH: EsSearch,
        PathValues.ES_RAW: EsRaw,
        PathValues.PERSONAS_LAYOUT_PARAMS: PersonasLayoutParams,
        PathValues.PERSONAS_SITES_ID: PersonasSitesId,
        PathValues.APPLICATION_WADL_PATH: ApplicationWadlPath,
        PathValues.APPLICATION_WADL: ApplicationWadl,
    }
)
