# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

import unittest

import dotcms_rest_client
from dotcms_rest_client.model.event_output import EventOutput
from dotcms_rest_client import configuration


class TestEventOutput(unittest.TestCase):
    """EventOutput unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
