# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

import unittest

import dotcms_rest_client
from dotcms_rest_client.model.add_variant_form import AddVariantForm
from dotcms_rest_client import configuration


class TestAddVariantForm(unittest.TestCase):
    """AddVariantForm unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
