# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.persona_content_type import PersonaContentType
from openapi_client import configuration


class TestPersonaContentType(unittest.TestCase):
    """PersonaContentType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
