# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

import unittest

import dotcms_rest_client
from dotcms_rest_client.model.login_as_form import LoginAsForm
from dotcms_rest_client import configuration


class TestLoginAsForm(unittest.TestCase):
    """LoginAsForm unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
