# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.response_entity_view_map_string_object import ResponseEntityViewMapStringObject
from openapi_client import configuration


class TestResponseEntityViewMapStringObject(unittest.TestCase):
    """ResponseEntityViewMapStringObject unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
