from dotcms_rest_client.paths.v1_sites_site_id_ruleengine_conditions_condition_id_condition_values_value_id.get import ApiForget
from dotcms_rest_client.paths.v1_sites_site_id_ruleengine_conditions_condition_id_condition_values_value_id.put import ApiForput
from dotcms_rest_client.paths.v1_sites_site_id_ruleengine_conditions_condition_id_condition_values_value_id.delete import ApiFordelete


class V1SitesSiteIdRuleengineConditionsConditionIdConditionValuesValueId(
    ApiForget,
    ApiForput,
    ApiFordelete,
):
    pass
