# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from dotcms_rest_client.paths.content_can_lock_params.put import CanLockContent
from dotcms_rest_client.paths.content_params.get import GetContent
from dotcms_rest_client.paths.content_indexcount_query.get import IndexCount
from dotcms_rest_client.paths.content_indexsearch_query_sortby_sortby_limit_limit_offset_offset.get import IndexSearch
from dotcms_rest_client.paths.content_lock_params.put import LockContent
from dotcms_rest_client.paths.content__search.post import Search
from dotcms_rest_client.paths.content_params.post import SinglePost
from dotcms_rest_client.paths.content_params.put import SinglePut
from dotcms_rest_client.paths.content_unlock_params.put import UnlockContent


class ContentDeliveryApi(
    CanLockContent,
    GetContent,
    IndexCount,
    IndexSearch,
    LockContent,
    Search,
    SinglePost,
    SinglePut,
    UnlockContent,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
