# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import openapi_client
from openapi_client.paths.content_indexsearch_query_sortby_sortby_limit_limit_offset_offset import get  # noqa: E501
from openapi_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestContentIndexsearchQuerySortbySortbyLimitLimitOffsetOffset(ApiTestMixin, unittest.TestCase):
    """
    ContentIndexsearchQuerySortbySortbyLimitLimitOffsetOffset unit test stubs
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 0




if __name__ == '__main__':
    unittest.main()
