# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class PushPublishBean(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            whereToSend = schemas.StrSchema
            publishDate = schemas.StrSchema
            publishTime = schemas.StrSchema
            expireDate = schemas.StrSchema
            expireTime = schemas.StrSchema
            neverExpire = schemas.StrSchema
            filterKey = schemas.StrSchema
            iWantTo = schemas.StrSchema
            timezoneId = schemas.StrSchema
            iwantTo = schemas.StrSchema
            __annotations__ = {
                "whereToSend": whereToSend,
                "publishDate": publishDate,
                "publishTime": publishTime,
                "expireDate": expireDate,
                "expireTime": expireTime,
                "neverExpire": neverExpire,
                "filterKey": filterKey,
                "iWantTo": iWantTo,
                "timezoneId": timezoneId,
                "iwantTo": iwantTo,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["whereToSend"]) -> MetaOapg.properties.whereToSend: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["publishDate"]) -> MetaOapg.properties.publishDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["publishTime"]) -> MetaOapg.properties.publishTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expireDate"]) -> MetaOapg.properties.expireDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expireTime"]) -> MetaOapg.properties.expireTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["neverExpire"]) -> MetaOapg.properties.neverExpire: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filterKey"]) -> MetaOapg.properties.filterKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iWantTo"]) -> MetaOapg.properties.iWantTo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timezoneId"]) -> MetaOapg.properties.timezoneId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iwantTo"]) -> MetaOapg.properties.iwantTo: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["whereToSend", "publishDate", "publishTime", "expireDate", "expireTime", "neverExpire", "filterKey", "iWantTo", "timezoneId", "iwantTo", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["whereToSend"]) -> typing.Union[MetaOapg.properties.whereToSend, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["publishDate"]) -> typing.Union[MetaOapg.properties.publishDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["publishTime"]) -> typing.Union[MetaOapg.properties.publishTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expireDate"]) -> typing.Union[MetaOapg.properties.expireDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expireTime"]) -> typing.Union[MetaOapg.properties.expireTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["neverExpire"]) -> typing.Union[MetaOapg.properties.neverExpire, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filterKey"]) -> typing.Union[MetaOapg.properties.filterKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iWantTo"]) -> typing.Union[MetaOapg.properties.iWantTo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timezoneId"]) -> typing.Union[MetaOapg.properties.timezoneId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iwantTo"]) -> typing.Union[MetaOapg.properties.iwantTo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["whereToSend", "publishDate", "publishTime", "expireDate", "expireTime", "neverExpire", "filterKey", "iWantTo", "timezoneId", "iwantTo", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        whereToSend: typing.Union[MetaOapg.properties.whereToSend, str, schemas.Unset] = schemas.unset,
        publishDate: typing.Union[MetaOapg.properties.publishDate, str, schemas.Unset] = schemas.unset,
        publishTime: typing.Union[MetaOapg.properties.publishTime, str, schemas.Unset] = schemas.unset,
        expireDate: typing.Union[MetaOapg.properties.expireDate, str, schemas.Unset] = schemas.unset,
        expireTime: typing.Union[MetaOapg.properties.expireTime, str, schemas.Unset] = schemas.unset,
        neverExpire: typing.Union[MetaOapg.properties.neverExpire, str, schemas.Unset] = schemas.unset,
        filterKey: typing.Union[MetaOapg.properties.filterKey, str, schemas.Unset] = schemas.unset,
        iWantTo: typing.Union[MetaOapg.properties.iWantTo, str, schemas.Unset] = schemas.unset,
        timezoneId: typing.Union[MetaOapg.properties.timezoneId, str, schemas.Unset] = schemas.unset,
        iwantTo: typing.Union[MetaOapg.properties.iwantTo, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PushPublishBean':
        return super().__new__(
            cls,
            *_args,
            whereToSend=whereToSend,
            publishDate=publishDate,
            publishTime=publishTime,
            expireDate=expireDate,
            expireTime=expireTime,
            neverExpire=neverExpire,
            filterKey=filterKey,
            iWantTo=iWantTo,
            timezoneId=timezoneId,
            iwantTo=iwantTo,
            _configuration=_configuration,
            **kwargs,
        )
