# coding: utf-8

"""
    dotCMS REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class WorkflowStepAddForm(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "escalationAction",
            "escalationTime",
            "stepName",
            "schemeId",
            "enableEscalation",
            "stepResolved",
        }
        
        class properties:
            schemeId = schemas.StrSchema
            stepName = schemas.StrSchema
            enableEscalation = schemas.BoolSchema
            escalationAction = schemas.StrSchema
            escalationTime = schemas.StrSchema
            stepResolved = schemas.BoolSchema
            __annotations__ = {
                "schemeId": schemeId,
                "stepName": stepName,
                "enableEscalation": enableEscalation,
                "escalationAction": escalationAction,
                "escalationTime": escalationTime,
                "stepResolved": stepResolved,
            }
    
    escalationAction: MetaOapg.properties.escalationAction
    escalationTime: MetaOapg.properties.escalationTime
    stepName: MetaOapg.properties.stepName
    schemeId: MetaOapg.properties.schemeId
    enableEscalation: MetaOapg.properties.enableEscalation
    stepResolved: MetaOapg.properties.stepResolved
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["schemeId"]) -> MetaOapg.properties.schemeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stepName"]) -> MetaOapg.properties.stepName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enableEscalation"]) -> MetaOapg.properties.enableEscalation: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["escalationAction"]) -> MetaOapg.properties.escalationAction: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["escalationTime"]) -> MetaOapg.properties.escalationTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stepResolved"]) -> MetaOapg.properties.stepResolved: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["schemeId", "stepName", "enableEscalation", "escalationAction", "escalationTime", "stepResolved", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["schemeId"]) -> MetaOapg.properties.schemeId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stepName"]) -> MetaOapg.properties.stepName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enableEscalation"]) -> MetaOapg.properties.enableEscalation: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["escalationAction"]) -> MetaOapg.properties.escalationAction: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["escalationTime"]) -> MetaOapg.properties.escalationTime: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stepResolved"]) -> MetaOapg.properties.stepResolved: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["schemeId", "stepName", "enableEscalation", "escalationAction", "escalationTime", "stepResolved", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        escalationAction: typing.Union[MetaOapg.properties.escalationAction, str, ],
        escalationTime: typing.Union[MetaOapg.properties.escalationTime, str, ],
        stepName: typing.Union[MetaOapg.properties.stepName, str, ],
        schemeId: typing.Union[MetaOapg.properties.schemeId, str, ],
        enableEscalation: typing.Union[MetaOapg.properties.enableEscalation, bool, ],
        stepResolved: typing.Union[MetaOapg.properties.stepResolved, bool, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WorkflowStepAddForm':
        return super().__new__(
            cls,
            *_args,
            escalationAction=escalationAction,
            escalationTime=escalationTime,
            stepName=stepName,
            schemeId=schemeId,
            enableEscalation=enableEscalation,
            stepResolved=stepResolved,
            _configuration=_configuration,
            **kwargs,
        )
